### ISSUE TITLE
some urls are not anomymized, repo name can be seen in the status bar or after clicking

### ISSUE THREAD

**Issue by monperrus** [tdurieux/anonymous_github#1]
unknown extension: replace download link by

    unknown extension, unable to anonymize (known extensions md/txt/json/java/...)

too big file:

    file too big to be anonymized (beyond 1MB, Github limit)

**Comment by monperrus** [comment]
to be closed?

**Comment by tdurieux** [comment]
Close with #30b8c53896ba3f686a737871e6b62adedac0e529
