### ISSUE TITLE
Anonimyzed repository does not fetch the last version.

### ISSUE THREAD

**Issue by cmougan** [tdurieux/anonymous_github#101]
I anonymized a repo few months ago.

I have tried several things today to incorporate changes:
 - Force update
 - Edit commit ID
 - Delete and create a new repo.

Still the original repo appears. (not the changes I committed this morning)

**Comment by cmougan** [comment]
Apparently the solution is to wait and don't be very impatient.

**Comment by TheMikeMerrill** [comment]
Hey, how long did it take for your repo to update? I'm wondering if I'm experiencing the same issue or if something else is going on.

**Comment by tdurieux** [comment]
It will update once a day each time someone visits your repo.

**Comment by TheMikeMerrill** [comment]
@tdurieux Thanks so much for maintaining this service - it's hugely useful and I really appreciate your work.

It doesn't seem like my repo (FluStudy-E079) wants to update. I've tried enabling auto-updates, changing and rechanging the branch, clearing my browser cache, and waiting over 24 hours. Am I missing something? Thanks :)

**Comment by tdurieux** [comment]
Can you check now?

**Comment by TheMikeMerrill** [comment]
That did the trick, thanks!
