### ISSUE TITLE
Notebook is rendered twice

### ISSUE THREAD

**Issue by sidv23** [tdurieux/anonymous_github#102]
**Issue:**
`ipynb` notebook is rendered twice on the anonymized repo. 

**Steps to reproduce:**
1. Create and run a Jupyter notebook `test.ipynb` with the following code:

```python
import numpy as np
import math
from matplotlib import pyplot as plt

x = np.array([ [math.cos(x), math.sin(x)] for x in np.linspace(0, 2*math.pi, num=50) ])
print(x)

plt.scatter(x[:,0], x[:,1])
```
2. Push to a git repo, and then anonymize. 

**Result:**
The nbviewer backend displays the contents of `test.ipynb` twice on the same page. 

**Expected results:**
`test.ipynb` should have one print statement and one plot displayed in the notebook. 

**MWE:**
[Anonymized Repo](https://anonymous.4open.science/r/anonymized-162E/anonymized.ipynb)
[Nbviewer](https://nbviewer.org/urls/anonymous.4open.science/r/anonymized-162E/anonymized.ipynb)

P.S. Thank you for the hard work and making this amazing resource!

**Comment by tdurieux** [comment]
[This is ](https://anonymous.4open.science/r/anonymized-162E/anonymized.ipynb) the link to the view, it is not the link to the file itself.
