### ISSUE TITLE
Excessive privileges required

### ISSUE THREAD

**Issue by LilithHafner** [tdurieux/anonymous_github#103]
To use this service requires authorizing read and write access to public and private repositories. Write access is certainly unnecessary, and private repositories could be on a case-by-case basis.

I get this when I click the login link on https://anonymous.4open.science/

"Anonymous Github by [tdurieux](https://github.com/tdurieux)
wants to access your LilithHafner account
Repositories
Public and private
This application will be able to read and write all public and private repository data. This includes the following:

Code
Issues
Pull requests
Wikis
Settings
Webhooks and services
Deploy keys
Collaboration invites"

<img width="1123" alt="Screen Shot 2022-02-04 at 7 24 08 PM" src="https://user-images.githubusercontent.com/60898866/152623343-b040329a-5515-4fdd-b3b9-cd558e6a074a.png">

**Comment by tdurieux** [comment]
Unfortunately, GitHub api does not allow me to select more precise permission (the permission system of github sucks...). I need to request for those permissions if I want to have access to private repos. 

Unfortunately, I cannot do anything about it until Github improve their API.

**Comment by coolharsh55** [comment]
Thanks - I understand. Though having write access to any repo is quite scary from a security perspective.

**Comment by tdurieux** [comment]
I completely get that, I am unhappy with this too, and I hope that GitHub will fix this issue in the future. 

Until then I need to deal with the current limitation and the limited amount of time/money I have for this side project.

I will add an explanation to the FAQ.

I could also create a hack that allows you to connect only with the public_repo write with a hidden URL, but this will be a mess for you if one day you want to anonymize private repositories.

**Comment by coolharsh55** [comment]
Thanks (again).
If you've left an issue or comment somewhere for github to create the granular api - I can try to engage there. Also okay to help with the faq or any other details about this (I work with tech for gdpr and privacy stuff)

**Comment by tdurieux** [comment]
I think there are many issues one of them: https://github.com/orgs/community/discussions/23128
