### ISSUE TITLE
How to Completely Clear an Abandoned Repository？

### ISSUE THREAD

**Issue by Lyle0411** [tdurieux/anonymous_github#105]
One of the repositories I set up earlier expired, and I deleted it. Now I want to reuse its id, but it shows as used. Specifically, its id is CDAT.

**Comment by jjbrophy47** [comment]
Same, I would like to reuse the ID of a deleted and expired repository.

**Comment by vinitra** [comment]
Same! Please help!

**Comment by tdurieux** [comment]
Unfortunately, I willl not allow this since this can introduce some problems
