### ISSUE TITLE
multiple README[...] files in root lead to broken home

### ISSUE THREAD

**Issue by gabriben** [tdurieux/anonymous_github#109]
I have a repo with

```
README.Rmd
README.md
README_files
```

The latter is a folder. As a result the link of my anonymized repo points to
`https://anonymous.4open.science/r/MY_REPO/README.Rmd/README.md/README_files`

Could the link point strictly to README.md?

thx

**Comment by tdurieux** [comment]
That is a weird bug, I thought I handled that. Could you send me by email your repo?
