### ISSUE TITLE
error 504 when trying to login

### ISSUE THREAD

**Issue by hgoldspiel** [tdurieux/anonymous_github#111]
Hi there, I keep encountering an error when trying to use this tool. Just after clicking the link and logging into my GitHub, the following error 504 is produced. Any suggestions here? Thanks!

![image](https://user-images.githubusercontent.com/51832279/165763801-c2efa4d4-5599-4460-89b1-91b6c5dbfc06.png)

**Comment by echosum** [comment]
You can see my solution. It works normally.   https://github.com/echosum/clone-anonymousgithub.git

**Comment by tdurieux** [comment]
FIxed
