### ISSUE TITLE
The previously used anonymous URL has been deleted, but it still can't be used?

### ISSUE THREAD

**Issue by wywd** [tdurieux/anonymous_github#114]
Hello, I have a tough question. After deleting the anonymous item, I want to restore it again, but the previous URL can't be used. It shows: anonymous repository ID is already used! However, when I click the previous link, it shows that the repository is expired, indicating that the URL is not occupied. How can I restore it?

**Comment by boheumd** [comment]
Same problem here! Need to be answered!

**Comment by tdurieux** [comment]
Please send me an email with the github repo and the anonymized repo

**Comment by tdurieux** [comment]
You can also reactivate the removed repo when you change the filter in your dashboard.

**Comment by wywd** [comment]
The anonymized repo:&nbsp;https://anonymous.4open.science/r/R-2-Trans.
I have used a new：&nbsp;https://anonymous.4open.science/r/R2-Trans.&nbsp;
The actual github repo:&nbsp;https://github.com/wywd/R-2-Trans.
I want to reuse the original URL. Thanks.






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Thomas ***@***.***&gt;; 
发送时间: 2022年8月10日(星期三) 凌晨1:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tdurieux/anonymous_github] The previously used anonymous URL has been deleted, but it still can&#39;t be used? (Issue #114)





 
Please send me an email with the github repo and the anonymized repo

**Comment by tdurieux** [comment]
It works as expected, you setup an expiration date for the 2022-07-13, the date passed and therefore the repo as been removed. You can unable it by changing the expiration date in your dashboard.
