### ISSUE TITLE
a bit too eager / replacing word subsets?

### ISSUE THREAD

**Issue by amueller** [tdurieux/anonymous_github#12]
Hey. First off, this is amazing!
Second, I just reviewed a paper and it had ``adXXXced`` in the readme. That leaks some information about the authors. Maybe if the name is not delimited by word boundaries, we could check if it's part of a dictionary word?
Taking a step back: what was the motivation to not require word boundaries? File names and variable names?
I'm not sure how easy it is to have ``meandyou.py`` and not replace ``andy`` with ``XXX``. That would require trying to do segmentation on out-of-vocabulary words...

**Comment by tdurieux** [comment]
> what was the motivation to not require word boundaries?

Honestly, I did not really think about it. It was just more straightforward. 
For filenames, it can be a problem but I can have different rules for different environments.

**Comment by amueller** [comment]
That would make sense, I think. Would love to help but probably won't have the time :-/

**Comment by tdurieux** [comment]
I just added word boundaries around anonymized terms in the body of files. 
It should also work on http://anonymous.4open.science/

**Comment by amueller** [comment]
awesome, thanks!
