### ISSUE TITLE
Feature request to render .org-files

### ISSUE THREAD

**Issue by jgru** [tdurieux/anonymous_github#121]
Dear @tdurieux,

first of all, thank you for the creation and operation of this great project. 

I want to pose a feature request regarding the rendering of `.org`-files, since Github renders org-mode content (placed in `.org`-files) in a comparable manner to markdown content which is visually far more pleasing than viewing plain text.
Do you think that there is a possibility to achieve this in `anonymous_github` as well?

This feature would be especially helpful for researchers who want to present their results as literate programming (and anybody who writes readmes in org-mode-syntax) 

Thank you already in advance for considering this feature request. 

Best regards,
jgru

**Comment by tdurieux** [comment]
Hi Jan, it is possible and it seems easy enough for me to do it on Monday. 
I added the task to my todo list.

**Comment by jgru** [comment]
Hi Thomas, 

thank you very much for the reply and for your willingness to tackle this soon.
This is great to hear, I'm already looking forward to this feature! :)

Thanks again. 

Best regards,
Jan

**Comment by jgru** [comment]
Thanks a lot for adding this feature!
