### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by jeremyhengjm** [tdurieux/anonymous_github#125]
Hi there, I am not able to view my anonymized repo and log into the website. Would be grateful if you can help asap as I am relying on the links for a review process. Many thanks!

**Comment by server-python** [comment]
:'(

**Comment by hljames** [comment]
Same here!

**Comment by server-python** [comment]
There is a problem with the server :(

**Comment by server-python** [comment]
follow me :)

**Comment by wanrenjie** [comment]
same here

**Comment by jiaor17** [comment]
same here!

**Comment by KimMeen** [comment]
same here and request emergent help to bring the server back online. Many thanks!

**Comment by tdurieux** [comment]
Should be fixed

**Comment by server-python** [comment]
Has someone hacked the server?:|
