### ISSUE TITLE
Could you help me recover the removed project or removed the existed anonymous url?

### ISSUE THREAD

**Issue by fly-dragon211** [tdurieux/anonymous_github#131]
After I deleted a project, I couldn't create a new project with same name. Could you help me recover the removed project or removed the existed anonymous url. So that I could create a new anonymous project. Thank you very much.

![image](https://user-images.githubusercontent.com/55907441/185733321-d078ec36-f8ce-43e2-a0a4-a304eff03906.png)

**Comment by tdurieux** [comment]
You can see your removed project in your dashboard by modifying the filters to include removed projects.
<img width="467" alt="image" src="https://user-images.githubusercontent.com/5577568/185733774-e8870645-d9ef-425a-8d0c-35c74fd87eb9.png">
