### ISSUE TITLE
Pointing to particular lines in the URL

### ISSUE THREAD

**Issue by davfuenmayor** [tdurieux/anonymous_github#134]
Unfortunately directly pointing to lines does not seem to be supported. For instance, this does not automatically scroll up to line 381 (and highlight 381 to 384) in the file as it would do in GitHub: https://anonymous.4open.science/r/840c8c57-3c32-451e-bf12-0e20be300389/package-lock.json#L381-L384  

This is a pity since this functionality is fundamental for directing readers/reviewers to the right parts of a file

**Comment by tdurieux** [comment]
It is an interesting feature, if you have some time it would be nice if you can have a look at it.
