### ISSUE TITLE
ERRORS.API rate limit exceeded for user ID 63538191.

### ISSUE THREAD

**Issue by HaoyiZhu** [tdurieux/anonymous_github#136]
When I try to view my anonymous repo, it shows this error.
![image](https://user-images.githubusercontent.com/63538191/188579810-7a78c119-3b15-4ce9-b588-4a8615bbe0e2.png)

**Comment by HaoyiZhu** [comment]
And when I click `login`, it shows `Internal Server Error`.

Actually several days ago I met with the same problem, but it becomes OK after one day. However, it occurs again today. Why does this problem happen and is there any solutions? By the way, I did no changes to my repo at all in these days.

Hope someone can help me. Thanks!

**Comment by tdurieux** [comment]
It should be fixed now
