### ISSUE TITLE
Still ERRORS.API rate limit exceeded for user ID 63538191.

### ISSUE THREAD

**Issue by HaoyiZhu** [tdurieux/anonymous_github#138]
#136 Still the same. I still see the error and again when I click login in it shows "Internal Server Error". @tdurieux Does this case only occur on me or on everyone else who want to see my repo?

**Comment by HaoyiZhu** [comment]
Since I have added the link to a submitted paper which is being reviewed, I really wonder that can the reviewers see my anonymous repo. Thanks!

**Comment by tdurieux** [comment]
can you send me a screen capture? The only way this happens now is if you do 1000requests in 15min.

**Comment by HaoyiZhu** [comment]
The error changes just now. Now it is like this:
![image](https://user-images.githubusercontent.com/63538191/188901228-7e84736c-0a72-4195-a58d-51899e485466.png)
I definitely did not do 1000 requests.

**Comment by HaoyiZhu** [comment]
The most confusing thing is that I cannot login my account. After I click login, it will show this:
![image](https://user-images.githubusercontent.com/63538191/188901522-2afaf8f8-9423-4be4-8bb8-3a8c035924d0.png)

**Comment by HaoyiZhu** [comment]
Oh, it works just now. I'm not sure what happened.

**Comment by tdurieux** [comment]
Are you mining github with your account?
if yes, this explain the problem

**Comment by HaoyiZhu** [comment]
Actually, I am indeed requesting GitHub API frequently for one project. So the anonymous repo needs my account's API call? If so, can other people see my repo normally?

**Comment by tdurieux** [comment]
Once your repo is cached it will not do many requests but at the beginning, it will do.
I used your OAuth token to do the request (it is how I have access to your private repo) but it also means that it shares your github quota.

**Comment by HaoyiZhu** [comment]
I see. So if my account is out of rate limit, then all people cannot see my anonymous repo, right?

**Comment by tdurieux** [comment]
not necessarily since I cache the content of your repo.

**Comment by HaoyiZhu** [comment]
I see. Thanks for your quick and kind reply!
