### ISSUE TITLE
Anonymize whole URLs

### ISSUE THREAD

**Issue by remram44** [tdurieux/anonymous_github#14]
If a link is to a URL that partially matches a pattern I want to hide, the whole URL should probably be anonymized. Right now, I get `engineering.xxx.edu`, which causes the following issues:
* xxx might be a registered domain (`xxx.edu` doesn't exist, but it's the case for `.com` and a few other)
* those domains **are usually pornographic** (please don't make my repository link to pornographic material :wink:)
* the remaining parts of the URL are still there, and can be used to de-anonymize (not all companies have an `.edu` domain, or an `engineering` subdomain)

The link is broken anyway, better to anonymize completely. Also, it could point to a page/popup saying it's been anonymized, instead of leading to an error page, so the reader knows what's going on.

**Comment by tdurieux** [comment]
good point!

I like the idea to remove the links that contain anonymized terms. I did not find yet a technique that could do it without having a big performance impact.

Thank you for the issue.
