### ISSUE TITLE
Fix link targets when handling org-mode files

### ISSUE THREAD

**Issue by jgru** [tdurieux/anonymous_github#140]
Dear @tdurieux,

you implemented support for rendering of org-mode files  in [51d9aa7](https://github.com/tdurieux/anonymous_github/commit/51d9aa7a1751e4a9715565f0040edf04511d3278). It is great so far, however, there remains an issue with the link targets in the table of contents. Unfortunately, neither the auto-generated TOC (`#+OPTIONS: toc`) nor the syntax commonly used in GitHub readmes are currently working.  E.g., I would expect the following snippet to correctly link to the respective headline: 
```org-mode
* TOC :TOC:
- [[#a][A]]
- [[#b][B]]
- [[#c][C]]
``` 
I shall be obliged if you could fix the link handling. 

Thanks again for providing `anonymous_github.`

Best regards,
jgru

**Comment by tdurieux** [comment]
I fixed the issue, it should work now.

**Comment by jgru** [comment]
Thank you very much, @tdurieux !
