### ISSUE TITLE
Repo expired issue

### ISSUE THREAD

**Issue by yl3394** [tdurieux/anonymous_github#141]
I created my own anonymous github at https://anonymous.4open.science/r/GraphSNML-NCD
I found out that it expired a month ago so I extended the expiration date to Dec this year. However, even after force refresh the dashboard still shows that my repo expired although the expiration date is in Dec this year. 

Could you take a look? Really appreciate it since this is kinda urgent. Thank you!

**Comment by tdurieux** [comment]
You repository is accessible. There was a cache in your browser. You should be able to refresh and it will be accessible.
