### ISSUE TITLE
issue with ckpool submission while testing

### ISSUE THREAD

**Issue by developeralgo8888** [tdurieux/anonymous_github#143]
After reading your paper and then went to your github and  under implementation 

i am testing on a UBNTU 20.04 Linux PC and modified the Stratum.c
  ` server.sin_addr.s_addr` = inet_addr("54.89.191.69");   `
    
to ckpool solo ipv4 address solo4.ckpool.org

`server.sin_addr.s_addr` = inet_addr("51.81.56.15");  `

Then in miner.c  added my bitcoin address and password but i am getting Authorization submittion Error.

anything i need to modify ?

**Comment by tdurieux** [comment]
Please pay attention where you are submitted your issue this is the repository of anonymous GitHub not the paper that you are reading.
