### ISSUE TITLE
Problem when re generate anonymous project

### ISSUE THREAD

**Issue by for-just-we** [tdurieux/anonymous_github#144]
Hi, author. I recently come across a problem, I submit a paper and put a anonymous link in it, then when I update original git repo, the anonymous project has not updated following it. So I remove the anonymous project and try to anonymize a new one with the same ID, but I fail, because the ID already existed, is there any way to fix this. Because I really need the same ID as I already submit paper

**Comment by for-just-we** [comment]
I already enable removed repo, but the browser always display `The repository is expired`. How should I do?

**Comment by YifanXu74** [comment]
Hi, I have met the same problem. I solved it by opening  the link  on another computer. Maybe there was a cache in your browser. In fact the link is work. See this issue: https://github.com/tdurieux/anonymous_github/issues/141
Hope this could help you.

**Comment by for-just-we** [comment]
> Hi, I have met the same problem. I solved it by opening the link on another computer. Maybe there was a cache in your browser. In fact the link is work. See this issue: #141 Hope this could help you.

Thank you, it seems Firefox caches something it shouldn't, my link could be opened on another computer.

**Comment by DmsKinson** [comment]
I have the same problem: I deleted the project, and when I want to create a new one with the same ID, it says the ID is already used, and visiting the original link shows that the project has expired. Changing the device did not solve the problem. Can I regenerate the project using the original id?

**Comment by tdurieux** [comment]
You can do it yourself, in your dashboard you can unfilter removed repositories. You can then enable your repository.

**Comment by DmsKinson** [comment]
Thanks for the reply! I have solved it.

**Comment by zhangaiwei-lucky** [comment]
> You can do it yourself, in your dashboard you can unfilter removed repositories. You can then enable your repository.

Hi, I encountered the same issue, but changing devices didn’t solve it. Also, I couldn’t find the filtering option on the GitHub dashboard.
