### ISSUE TITLE
My repository still shows (preparing) after 4 hours.

### ISSUE THREAD

**Issue by vrthra** [tdurieux/anonymous_github#146]
Hello,
    I attempted to refresh my repository [https://anonymous.4open.science/r/chaos-replication-848B](https://anonymous.4open.science/r/chaos-replication-848B),  but it still shows (preparing) after 4 hours.

**Comment by zhengchen1999** [comment]
Hi, I have met the same problem. And create a new project; it also shows "Preparing."

**Comment by zhengchen1999** [comment]
The website has recovered.

**Comment by tdurieux** [comment]
Many submission happened at the same time with some of the repositories that took a really long time.
