### ISSUE TITLE
different formatting in markdown file between original repo and anonymous one

### ISSUE THREAD

**Issue by EmanueleFrancazi** [tdurieux/anonymous_github#148]
I've created an anonymous version of my GitHub repo. The repo include a README.md file.
In the GitHub version the file works properly; for example the math between "$" symbols is shown properly.
When I access the anonymous version the same expression doesn't appear formatted.
How can I solve this?

**Comment by tdurieux** [comment]
By finding the good markdown formatting library

**Comment by EmanueleFrancazi** [comment]
Thanks @tdurieux for your reply!
could you elaborate a bit more on this? Is the first time I approach markdown, so I'm newcomer.
If I understood correctly the problem is that the markdown I used for the README.md file in GitHub (github flavored markdown) is not the same dialect supported on anonymous github; this is why the math expressions, for example, don't appear properly on the anonymous clone of the repo. Is it correct?
Is there a way to set on anonymous GitHub (or in the .md file) GFM so that I see exactly the same formatting in the original repo and in the anonymous clone?

**Comment by tdurieux** [comment]
The markdown is the same but the rendering agent is different and therefore it exists difference between anonymous GitHub and GitHub

**Comment by EmanueleFrancazi** [comment]
what is the correct way to make math formula appear properly on markdown file in anonymous github?

**Comment by tdurieux** [comment]
I don't know. It is what I asked you to investigate.

**Comment by EmanueleFrancazi** [comment]
How could one figure it out this?  
Standard markdown syntax (as `$expression$` or  `\\( expression \\)` ) does not seems to work and I was not able to find a guide for the specific case.

**Comment by tdurieux** [comment]
I just added the support for Math expressions in Markdown.
