### ISSUE TITLE
Auto update option is not persistent

### ISSUE THREAD

**Issue by EmanueleFrancazi** [tdurieux/anonymous_github#149]
Hi,
I ticked the option `Auto update` in the default setting (feature section) in order to keep my anonymous repo updated with the commit of the original one.
The problem is that once set the option `Auto update` (and saved the changes with the `Save` on the lower left) doesn't stay active, i.e. once I leave the setting section and come back  `Auto update`  option is not active anymore.
How should I proceed to make it persistent?

**Comment by tdurieux** [comment]
The part of the site is broken, you should update each repository for now

**Comment by EmanueleFrancazi** [comment]
Ok, thank you for the claryfication!
