### ISSUE TITLE
Provide a Docker image

### ISSUE THREAD

**Issue by nuest** [tdurieux/anonymous_github#15]
Good idea! IMO any publisher with a blind review process should host this one.

A Docker image might help more people providing this service. Have you thought about publishing one?

**Comment by tdurieux** [comment]
I did not think about it, by I can definitely create one.

Thank you for the idea

**Comment by tdurieux** [comment]
I just created a Docker image for the project and I pushed it on dockerhub: https://hub.docker.com/r/tdurieux/anonymous_github/

**Comment by nuest** [comment]
Cool. I recommend making it an automated build, I personally would not use your image since I don't know the Dockerfile that it is based on..

**Comment by tdurieux** [comment]
I would not trust an automated build... since I can overwrite the images...
The only way to ensure the validity of the image is to inspect it.
