### ISSUE TITLE
How to delete a repo that shows preparing for a long time?

### ISSUE THREAD

**Issue by monsterandy** [tdurieux/anonymous_github#150]
I tried to anonymize a repo with probably too many files, and it shows in the "preparing" status for a long time. I could not check the progress, and no errors were showing. The options button only offers "Edit" and "View Repo" options, but no remove option. Is there a way I can stop preparing this repo and delete it so I can reuse the anonymized repository id?

**Comment by tdurieux** [comment]
I don't have this option for the moment but i fixed the issue on your repo and it is now accessible.
