### ISSUE TITLE
Can this project support release?

### ISSUE THREAD

**Issue by Luciennnnnnn** [tdurieux/anonymous_github#161]
I want to provide my pretrained models in release since Google Drive will reveal owner's identity,

If this is not possible, what's the usual solution?

Thansk.

**Comment by LuoXin-s** [comment]
Ok, thanks for suggestion. Before try that, I have tried using git-lfs to store models in my git project directly, does this also has cost on you or on GitHub?

**Comment by tdurieux** [comment]
I need to store
