### ISSUE TITLE
Issue replacing keywords containing brackets

### ISSUE THREAD

**Issue by Maximvdw** [tdurieux/anonymous_github#162]
Hi,

I have a use case where I am replacing keywords of a company/lab/university. The keyword includes brackets `()` to also anonymise
the abbreviation without having to specify the abbreviation alone (which could replace unwanted parts).

I created an example here:
https://github.com/Maximvdw/example-bug/blob/main/index.html
The example contains a few tests, because I was first not sure if it was due to the HTML encoded &amp; or the <a> tag  

This is the anonymisation result where you can see test 5, 6, 7 and 8 fail due to the brackets:
https://anonymous.4open.science/w/example-bug-FD4B/index.html

Using the following keywords
```
Web &amp; Information Systems Engineering Lab
Web & Information Systems Engineering Lab
Web &amp; Information Systems Engineering (WISE) Lab
Web & Information Systems Engineering (WISE) Lab
```

My best bet is that the () is not escaped when using it in the regex replace. However, I was not sure if there was already a function/place where other characters were replaced.

Kind regards,
Maxim

**Comment by tdurieux** [comment]
It was on purpose that the terms are interpreted as regex. 
I would like to keep it that way.

I think a better option would be to add a warning when a regex character is detected in the terms field.

WDYT?

**Comment by Maximvdw** [comment]
So I have two sides for this answer:

1) For some reason my mind did not see that I could actually use regexp and shorten the list that I currently have by quite a bit.
So in that way, it seems like its best to keep the current functionality. However, it was not clear to me that this was even possible. 

2) I can imagine that regular expressions is not for everyone, especially if you are using github for datasets, etc.... In which case some people might struggle to anonymise their repo.

So for now, I would say to keep it - but maybe in the future when there is time, it would be a good idea to maybe have a checkbox under "advanced options" to interpret the terms as regular expressions (default) or not.

**Comment by tdurieux** [comment]
I added a warning message when a regex character is detected.
<img width="283" alt="image" src="https://user-images.githubusercontent.com/5577568/216641060-a3c13f8d-44fa-4d6b-a7c2-d35770b71223.png">
