### ISSUE TITLE
Anonymization of organization's private repositories

### ISSUE THREAD

**Issue by Malix-Off** [tdurieux/anonymous_github#168]
Hello!
Is it possible to anonymize organization's private repositories?
I didn't succeeded doing so, even though my account does own the organization

**Comment by tdurieux** [comment]
Yes it is possible. But some organization forbid the access to third party applications.

**Comment by Malix-Off** [comment]
> Yes it is possible. But some organization forbid the access to third party applications.

Weird, I didn't touched anything in my organization.
I checked and apparently the org isn't forbidding access to third party apps either

**Comment by Malix-Off** [comment]
> Indeed, could you try again and send me the repo that you want to anonymize by email?

Sure, I will do it asap when I get home and will let you know.

**Comment by Maximvdw** [comment]
I've had some issues before where I logged into anonymous github -> created a new organisation after my first login and had to remove it as a third party service.

Remove Anonymous github from "Authorized OAuth apps"
https://github.com/settings/applications

and login again. You will not lose any settings or repositories.

**Comment by Malix-Off** [comment]
> I've had some issues before where I logged into anonymous github -> created/joined a new organisation after my first login and had to remove it as a third party service because the scope did not include the newly joined organisation.
> 
> 1. Logout from anonymous github
> 2. Remove Anonymous github from "Authorized OAuth apps"
>    https://github.com/settings/applications
> 3. and login again. You will not lose any settings or repositories. During the login you are then able to select to which organisations anonymous github has access.
> 
> PS: Maybe a "reauth" button or something would prevent this workaround
> 
> EDIT: You can also click on the Anonymous github application https://github.com/settings/connections/applications/be3b7f49214bec8f58f6 to grant access

Worked, thanks!
Maybe this contribution could be added to the FAQ, it would be sweet!

**Comment by vmikk** [comment]
Unfortunately, I have the same issue with authorizing organization's private repository.
I'm getting the following error: `https://github.com/... does not exist or is not accessible`.
I tried to logout, remove Anonymous github from "Authorized OAuth apps", and add it back (granting permission for the organization), but it does not work.
In addition, I even removed application access restrictions in OAth application policy in organization settings, but it does not have an effect.

**Comment by tdurieux** [comment]
Is your repository part of an organization that restricts  access to third party apps?

**Comment by vmikk** [comment]
No, we are using default settings.
![image](https://github.com/tdurieux/anonymous_github/assets/7162120/14755f78-64da-49c7-8bd3-f7203c558f19)

But in addition, I also tried to remove any restrictions.

**Comment by tdurieux** [comment]
Not sure why it is not working, but github does not give me access to that repo with your account.

**Comment by jyhong836** [comment]
I encounter the same problem.

**Comment by muehlber** [comment]
Could you possibly add the link from @Maximvdw's post (Feb 14, 2023) to re-configure access to the FAQ? Took me ages to find this.
