### ISSUE TITLE
Feature request - support for Github emoticons in markdown

### ISSUE THREAD

**Issue by Maximvdw** [tdurieux/anonymous_github#169]
Hi,

Github supports markdown emoticons on markdown files (this is not supported on github pages, so only repository view) ✅. 

My (low priority) feature request is to add:
https://www.npmjs.com/package/marked-emoji
In combination with OctoKit to add supported for these emojis in markdown files.

An example for Github emojis is given on the marked-emoji npm page. 

Kind regards,
Maxim Van de Wynckel

**Comment by tdurieux** [comment]
Anonymous GitHub now supports emojis in markdown!

[8ac3a66](https://github.com/tdurieux/anonymous_github/commit/8ac3a66a301472d491850d8801956daee59d8919) closes/
