### ISSUE TITLE
Feature Request: Raw File Support

### ISSUE THREAD

**Issue by Malix-Off** [tdurieux/anonymous_github#171]
Like how github handles [raw](https://docs.github.com/en/enterprise-cloud@latest/repositories/working-with-files/using-files/viewing-a-file#viewing-or-copying-the-raw-file-content)

**Comment by tdurieux** [comment]
The download button on the top right does that

**Comment by Malix-Off** [comment]
> The download button on the top right does that

Nope, that's download, not raw

**Comment by tdurieux** [comment]
You want to visualize the raw directly?

**Comment by Malix-Off** [comment]
> You want to visualize the raw directly?

nah it's for APIs

**Comment by tdurieux** [comment]
raw is the same as download. I don't see the difference, all rendering is done in the browser. The download button redirects you to the raw file (but anonymized)

**Comment by tdurieux** [comment]
Since you plan to use it as an API I really don't see the difference. The raw is just the download without an HTTP header.
Could you explain me what you plan to do with it?

**Comment by Malix-Off** [comment]
> Since you plan to use it as an API I really don't see the difference. The raw is just the download without an HTTP header. Could you explain me what you plan to do with it?

One is downloading, the other is basically a blank page with only the file content as html, nothing more, you do not download it.
but it's okay to not do it, np

**Comment by Malix-Off** [comment]
> > You want to visualize the raw directly?
> 
> Thus you want to do that.

what's intrest me is not visualisation but API fetching a script from the link directly

**Comment by Maximvdw** [comment]
For most frameworks (axios, node-fetch, jquery,...) the `content-disposition` should not really affect the output or performance? The main reason why Github has a "raw" view is because it has a lot of built-in ways to show different types of files (e.g. geojson files are shown as a map rather than a JSON file)

**Comment by tdurieux** [comment]
I added a view file button that allows displaying the raw content of the file. I open it helps you.
