### ISSUE TITLE
Feature Request: Clone Support

### ISSUE THREAD

**Issue by Malix-Off** [tdurieux/anonymous_github#172]
It would be very difficult, idk if it is even worth it to be honnest

**Comment by tdurieux** [comment]
If my solution was purely based on filesystem it would not be that difficult but since I made my life hard i don't think it is an option unfortunately

**Comment by Malix-Off** [comment]
> If my solution was purely based on filesystem it would not be that difficult but since I made my life hard i don't think it is an option unfortunately

lol ye

**Comment by tdurieux** [comment]
Duplicated with #24

**Comment by Malix-Off** [comment]
Close as "not planned" would have fit better
