### ISSUE TITLE
Bugs and enhancements: CLI changes

### ISSUE THREAD

**Issue by Maximvdw** [tdurieux/anonymous_github#174]
Hi,

After testing it, there are a few things I think could need some tweaking for the CLI tool to anonymise a repository locally:

1. Think this is a leftover from debugging, but anonymised directories are called "test" (https://github.com/tdurieux/anonymous_github/blob/main/cli.ts#L54)
2. Providing terms with a comma has a few issues, it creates very long commands (maybe support a config or txt with newlines?) and terms with a comma can not be escaped
3. Providing an output directory would be great
4. The output is zipped by default: https://github.com/tdurieux/anonymous_github/blob/main/cli.ts#L88 which for me was not needed. Maybe a --zip flag?
5. Some flags for the settings would be nice: https://github.com/tdurieux/anonymous_github/blob/main/cli.ts#L69 for example
6. The zip contains a folder "original" which seems misleading
7. I cannot seem to download another branch than master/main

Thanks for the cli update,
Maxim

**Comment by tdurieux** [comment]
1. In my head the cli would also be used to create a zip, the repo_id was irrelevant. I did not think that people would use it without a zip
2. I thought about it but did not have a better solution for the time being. 
3. Should be easy enough 
4. Related to 1.
5. I should be able to fix that one easily 
6. Did you provide a GitHub URL with a specific branch in the URL such as https://github.com/tdurieux/anonymous_github/tree/v1

**Comment by Maximvdw** [comment]
1. There is actually a "test" directory inside the zip file, which made it seem unintentional. Personally I modified it to `\`${ghURL.name}-${ghURL.branch}\``
As for using it as a ZIP, the only reason why I did not do it was because I had multiple repos that I wanted to place inside a single zip file. I also wanted to make sure that the data was correctly anonymised before I submitted it :)
6. Yes, ![](https://i.mvdw-software.com/Code_42U6xgK0M8.png) as you can see it uses the main repo and not the v1 repo

**Comment by tdurieux** [comment]
Pay attention the folder is not anonymized, it is really the original folder only the zip is.

**Comment by tdurieux** [comment]
The content of the zip is but not the content of the folder `repositories`.

**Comment by Maximvdw** [comment]
aha sorry, my mistake - well, did not find that folder so all is fine :)

**Comment by tdurieux** [comment]
I dont succeed to reproduce when the repo name in included in the zip. It is probably because you are on windows. Not sure how I can debug this.

**Comment by Maximvdw** [comment]
I can not test it today, but could it be that the forward slash on this line:
https://github.com/tdurieux/anonymous_github/blob/main/src/Repository.ts#L373

Causes issues with the `file.path.replace()` that returns a backslash on Windows?
https://github.com/tdurieux/anonymous_github/blob/main/src/storage/FileSystem.ts#L139

Might not have time this week to test it, but will see if I can troubleshoot it next week.

**Comment by Maximvdw** [comment]
after a very quick test I can confirm that the slash is the issue - will create a small PR
