### ISSUE TITLE
Broken  Repo

### ISSUE THREAD

**Issue by FreddieNeverLeft** [tdurieux/anonymous_github#177]
Hello, 

Thanks for your hard work on maintaining this, I have run into an issue similar to issue https://github.com/tdurieux/anonymous_github/issues/88 after a pull, my repo status seems to be stuck at 'Preparing'.
Could you please look into this? Much thanks!

**Comment by mnagired** [comment]
Same here, I am unable to update or create new repos. Thanks a lot for your help!

**Comment by tdurieux** [comment]
my server did not have memory, should be fine now.

**Comment by mnagired** [comment]
Thanks a lot!
