### ISSUE TITLE
why does the force update not work?

### ISSUE THREAD

**Issue by viocently** [tdurieux/anonymous_github#179]
I have updated my github repository many times, but after I clicked the force update, nothing changed in my anonymous repository.

**Comment by tdurieux** [comment]
> I have updated my github repository many times, but after I clicked the force update, nothing changed in my anonymous 
repository.

your repositories are already on the latest commits

**Comment by viocently** [comment]
> > I have updated my github repository many times, but after I clicked the force update, nothing changed in my anonymous
> > repository.
> 
> your repositories are already on the latest commits

But the content of my anonymous repository is totally different from the real github one.

**Comment by viocently** [comment]
> > I have updated my github repository many times, but after I clicked the force update, nothing changed in my anonymous
> > repository.
> 
> your repositories are already on the latest commits

A typical example is that, their README files have different content.

**Comment by iffatfatima** [comment]
same issue

**Comment by viocently** [comment]
> same issue, changes are not appearing with auto-update turned on or by force update

Is it possible that the force update works by when the auto update is turned off

**Comment by viocently** [comment]
This is not a issue caused by cache, as I have tested in a new computer. Though the commit HASH for the anonymous repository is right, the content is not updated even after one day.

**Comment by Jlutripper** [comment]
Same issus with README files update, you can directly see the change of other files, however the readme files remains old version

**Comment by Jlutripper** [comment]
Same issus with README files update, you can directly see the change of other files, however the readme files remains old version

**Comment by wykstc** [comment]
Yes, I meet the same problem. One of my project can work well but for another it cannot. Although I can find that in edit page the README can completely show, the README do not change in the repository.

**Comment by Jlutripper** [comment]
In order to update my readme files I had to delete and create a new repo, however the original repo seems could not completely delete so i could not create a repo as same id as the old one, so the link repo on the paper cannot be remake, could someone help?

**Comment by wykstc** [comment]
According to best of my knowledge, the original one cannot be deleted and can only be expired (to recover easily in future). The ID is unique. I think there are no methods to deal with it.

**Comment by Jlutripper** [comment]
> According to best of my knowledge, the original one cannot be deleted and can only be expired (to recover easily in future). The ID is unique. I think there are no methods to deal with it. You can only make changes on the original one.

Thanks a lot, i tried delete the readme file and git push again, amazingly the readme file is still the old one, i change the browser and clear the cache but its not work for me

**Comment by wykstc** [comment]
> > According to best of my knowledge, the original one cannot be deleted and can only be expired (to recover easily in future). The ID is unique. I think there are no methods to deal with it. You can only make changes on the original one.
> 
> Thanks a lot, i tried delete the readme file and git push again, amazingly the readme file is still the old one, i change the browser and clear the cache but its not work for me

兄弟这个是这样的，我也这样操作过，没有用的。

**Comment by Jlutripper** [comment]
i have tried delete my github repo and git push again but readme is still not change

**Comment by JonathanDZ** [comment]
My anonymous repo seems to be broken as well. I tried to update my anonymous repo with the force update button or directly paste my latest commit's SHA code in the repo's setting, and I cleared the browser's cache between each attempt. Neither method works for me. The only way to update my anonymous repo is to recreate a fresh new repo from scratch, but in this way, I can't keep the original link that I gave to my reviewer. I hope this can be fixed as soon as possible.

**Comment by viocently** [comment]
It seems the repo can only be updated once a day, and then the subsequent clicks on the force update button is considered invalid.

**Comment by JonathanDZ** [comment]
> It seems the repo can only be updated once a day, and then the subsequent clicks on the force update button is considered invalid.

If so, why showing the update success message? It's really confusing. Besides that, there is a notice on the setting page saying it can be updated once for an hour. Maybe I should wait another day to see whether it functions like you said. Anyway, thanks for your suggestion.

**Comment by Benature** [comment]
> It seems the repo can only be updated once a day, and then the subsequent clicks on the force update button is considered invalid.

I've tried the update over 24h.

**Comment by viocently** [comment]
> > It seems the repo can only be updated once a day, and then the subsequent clicks on the force update button is considered invalid.
> 
> I've tried the update over 24h.

Still not work, though?

**Comment by Benature** [comment]
> > > It seems the repo can only be updated once a day, and then the subsequent clicks on the force update button is considered invalid.
> > 
> > 
> > I've tried the update over 24h.
> 
> Still not work, though?

yep, nothing changed. It just fixs at a submit about two days ago.

**Comment by iffatfatima** [comment]
> > same issue, changes are not appearing with auto-update turned on or by force update
> 
> Is it possible that the force update works if the auto update is turned off

Auto-update is turned on. I even tried after 24 hours. It is not updating to the new version even with a force update.

**Comment by iffatfatima** [comment]
So I changed the Proxy mode to stream for my repository and after that, the force update worked.

**Comment by Benature** [comment]
When I click force update, the console print some errors.

![image](https://user-images.githubusercontent.com/35028647/220008222-16309345-5508-48b1-b25e-fa7b31bbc11d.png)

**Comment by Benature** [comment]
Even more strange, if I click `edit`, it will show the README.md file of the repo, which is the latest version. However, if I directly open the anonymous repo, the README.md is still out of date.

**Comment by Benature** [comment]
> So I changed the Proxy mode to stream for my repository; after that, the force update worked. I don't understand if that's how it is supposed to work in the first place. In any case, I hope this helps resolve issues for others.

The setting says that

>How the repository will be anonymized. Stream mode will request the content on the flight. This is the only option for repositories bigger than 7.3MiB. 
>Download will download the repository the repository on the anonymous.4open.science server, it is faster and offer more features.

I think it can explain why you can success.

However, I've tried to change the proxy mode to stream and force update again, the file content did not change. I guess somehow the page show the content still from anonymous.4open.science server, which fail to update content?

**Comment by Changgang-Zheng** [comment]
same problem +1

**Comment by tdurieux** [comment]
I just fixed the bug, plus force update your repository.
