### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by hendriks73** [tdurieux/anonymous_github#18]
<img width="1055" alt="screen shot 2019-02-11 at 10 01 29" src="https://user-images.githubusercontent.com/4749755/52553539-1a630080-2de4-11e9-9e13-ddb4d4a9afaf.png">

Just tried to use your service, but got a 500 Internal Server error. Any idea what's going wrong?

**Comment by tdurieux** [comment]
It is because your repository is empty. I will fix this bug. Thank you for the issue

**Comment by hendriks73** [comment]
> It is because your repository is empty.

Indeed it is. I haven't pushed the code yet...

> I will fix this bug. Thank you for the issue

I have to thank you!
