### ISSUE TITLE
Could you please help me update the repository manually?

### ISSUE THREAD

**Issue by viocently** [tdurieux/anonymous_github#180]
As I have said, the auto update does not work. But I have put the link of my anonymous repo in my paper and submitted, so could you please help me update my content to the latest? Just redownload the content from my github repo manually, if possible ...

**Comment by boyuanzhang62** [comment]
Same issue. Did it update after 24 hours?

**Comment by wykstc** [comment]
> As I have said, the auto update does not work. But I have put the link of my anonymous repo in my paper and submitted, so could you please help me update my content to the latest? Just redownload the content from my github repo manually, if possible ...

I wait for 24 hours, it still not work. You situation is the same as me. There is no content in README.

**Comment by tdurieux** [comment]
@wykstc you did not select the auto-update option.

**Comment by tdurieux** [comment]
> As I have said, the auto update does not work. But I have put the link of my anonymous repo in my paper and submitted, so could you please help me update my content to the latest? Just redownload the content from my github repo manually, if possible ...

change your tone, it is a free service that I handle during my free time. 

There is a bug, the code is open source feel free to fix it ;) I am waiting for your PR impatiently.
