### ISSUE TITLE
Content out of sync

### ISSUE THREAD

**Issue by arianeziehn** [tdurieux/anonymous_github#181]
Hey, I needed to update my data links in some shell and .md files in my repository. These files are not getting updated even after now waiting 24 hours to process my commits as well as creating and adding a new branch as the source to the anonymous repo.

**Comment by mnagired** [comment]
same issue here, my commits are not being propagated to the anonymous repository. I've selected auto-update and have tried to "force-update" many times as well. Could you please help out here @tdurieux ? Thanks for your time!

**Comment by Changgang-Zheng** [comment]
The same issue as well, please help! Thanks a lot!

**Comment by Hanrui-Wang** [comment]
Same issue here, please help. The repo is necessary to my paper submission. Thanks a lot!

**Comment by tdurieux** [comment]
I just fixed the bug, plus force update your repository.

**Comment by mnagired** [comment]
It works for me as well. Thanks a lot!
