### ISSUE TITLE
anonymous_github doesn't update with the latest commit

### ISSUE THREAD

**Issue by Xiao0728** [tdurieux/anonymous_github#186]
Hi, 

The anonymous_github for a code repository does not update automatically and does not appear to update even when forced.

Xiao

**Comment by tdurieux** [comment]
Can you check your repo?

**Comment by tdurieux** [comment]
Not sure what is happening there.

**Comment by tdurieux** [comment]
Should be fixed now.

**Comment by Xiao0728** [comment]
Yes, I have replaced the absolute hyperlinks with relative links. Thanks for your help! Cheers!

Xiao
