### ISSUE TITLE
markdown equation not properly shown

### ISSUE THREAD

**Issue by MasterXiong** [tdurieux/anonymous_github#191]
Hi, 

Thanks for sharing this useful tool! I tried to write some equation in a markdown file, and it display normally on the github website. But the equation is not properly displayed in the anonymous link, instead just displayed in its raw text format. Is this normal and how can I fix it? Thanks!

**Comment by tdurieux** [comment]
It is now supported with commit [3627096](https://github.com/tdurieux/anonymous_github/commit/3627096e63ffaf2f680a7fb3b7f96eb738ec93fc)
