### ISSUE TITLE
PDF is not updated.

### ISSUE THREAD

**Issue by gao462** [tdurieux/anonymous_github#192]
I have a PDF file in a sub directory, when I tried to update my annoymous directory, this PDF file will still be the old version. But if create a PDF file with latest content but use a different filename, the new file will be downloaded.
I wonder if there is any caching issue.

**Comment by tdurieux** [comment]
can you force refresh the page shift+ctrl+r or shift+cmd+r

**Comment by gao462** [comment]
It works for me. Thank you.
