### ISSUE TITLE
Existing files are not updated after force fresh

### ISSUE THREAD

**Issue by Wancen** [tdurieux/anonymous_github#194]
With the same commit, newly added files have shown in the anonymous git repo. But the changes on existing files haven't been reflected.

**Comment by GuillaumeHaben** [comment]
In my case it was updated after a few minutes, but indeed the "Force update" didn't update the existing files with changes.

**Comment by tdurieux** [comment]
Could you check now?

**Comment by Wancen** [comment]
It looks good now. Thanks
