### ISSUE TITLE
Gateway time-out

### ISSUE THREAD

**Issue by mujin2020** [tdurieux/anonymous_github#195]
Gateway time-out Error code 504

**Comment by tdurieux** [comment]
It is probably a memory issue, i don't succeed to identify the problem.

**Comment by mujin2020** [comment]
> It is probably a memory issue, i don't succeed to identify the problem.

Thank you for your prompt response. But I have tried different computers and browsers on different networks and all seem to have the same problem.

**Comment by tdurieux** [comment]
It is running now
