### ISSUE TITLE
Anonymous Github Audio Files on Page Don't Play

### ISSUE THREAD

**Issue by taubaaron** [tdurieux/anonymous_github#199]
Hi,

I have a repo with a results page (github.io) where I present audio files from my git. This works perfectly. 
Recently I made an anonymous git via https://anonymous.4open.science/ in order to share my results anonymously. Unfortunately the audio files don't play from the anonymous git's result page. 

I tried both:
            <audio controls preload="auto">
                <source src="sample_audio/audio1.wav" type="audio/wav">
                Your browser does not support the audio element.
            </audio>

and:
            <audio controls preload="none">
                <source src="sample_audio/audio1.wav" type="audio/wav">
                Your browser does not support the audio element.
            </audio>

Would appreciate any help on this. Thanks

**Comment by rasaSystemComplexity** [comment]
Hello,I got the same problem.I try to anonymous my repo,but it's created by github.io,How can I anonymous it?Could you please tell me?Thank you?

**Comment by taubaaron** [comment]
> Hello,I got the same problem.I try to anonymous my repo,but it's created by github.io,How can I anonymous it?Could you please tell me?Thank you?

1. Go to https://anonymous.4open.science/dashboard (login to your user)
2. For anonymized git from dashboard, on the right press "Action" -> "View Page" 
3. The anonymous "GitHub.io" page should show.

Note - if you don't have the option "View Page" make sure that in the repo settings you check the pages option

**Comment by tdurieux** [comment]
Could you share your repo for me to be able to test?

**Comment by taubaaron** [comment]
> Could you share your repo for me to be able to test?

Sure:
https://anonymous.4open.science/w/singit_results/

**Comment by tdurieux** [comment]
It is working on my side. It is not working for you?

**Comment by taubaaron** [comment]
Tried a different browser (chrome instead of Safari) and now it works. 
Thanks @tdurieux

**Comment by tdurieux** [comment]
@taubaaron I improved the support for safari and I also add a media player for the non github page view (using the default browser)
