### ISSUE TITLE
ERRORS.loading

### ISSUE THREAD

**Issue by reviewerchris** [tdurieux/anonymous_github#202]
Hello,
I have anonymized the github repository 
https://github.com/reviewerchris/repository_nhmc-ar_c1_c2_23_04_24_mon_20h40
using the words
dama
sinoquet
fatoumata
christine
nantes
ls2n

I obtained the repository 
https://anonymous.4open.science/r/repository_nhmc-ar_c1_c2_23_04_24_mon_20h40-B168

However, there are multiple issues:
I cannot open the file src/EM_learning.py as well as a lot of other files (ERRORS.loading),
whereas I can open some other files (for example gaussian_innovation.py).
I cannot explain the origin of these differences.

Can you help me please? What dit I miss?
I thank you in advance.
Best regards,
Christine Sinoquet

**Comment by tdurieux** [comment]
I will have a look

**Comment by tdurieux** [comment]
It is a weird bug, everything is working in my code but there is something that does not work between my server and the client (Nginx or Cloudflare). I continue to investigate

**Comment by tdurieux** [comment]
Same server, the same service but a different domain and it is working: https://beta.durieux.me/r/repository_nhmc-ar_c1_c2_23_04_24_mon_20h40-B168/mcnh-ar-C2_training.py. I do not explain this

**Comment by tdurieux** [comment]
It is now working on Chrome on my side but not on other browsers for some reasons.

**Comment by tdurieux** [comment]
@reviewerchris could you check if it is working for you?
