### ISSUE TITLE
Anonymous repo does not contain all files

### ISSUE THREAD

**Issue by garandria** [tdurieux/anonymous_github#203]
I updated my anonymized repository by editing its commit and it was fine. However, the anonymized repository does not contain all the files of the original repository at the given commit.

**Comment by tdurieux** [comment]
Can you send me your repo

**Comment by garandria** [comment]
Here the anonymized repository: https://anonymous.4open.science/r/pyro-5DCF/

**Comment by tdurieux** [comment]
which files are missing?

**Comment by garandria** [comment]
The readme, a directory of source code and another subdirectory of ~data/~

**Comment by tdurieux** [comment]
It should be fixed now.

**Comment by garandria** [comment]
Thank you very much.
