### ISSUE TITLE
Add video support

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [tdurieux/anonymous_github#204]
Hi,

Thanks for the project, github now supports videos in a project readme
Would it be possible to add support for them? 

https://github.blog/2021-05-13-video-uploads-available-github/

Kind regards,
Mark

**Comment by pseudo-rnd-thoughts** [comment]
I have created this public repo as an example - https://github.com/pseudo-rnd-thoughts/readme-video/blob/main/README.md

But I would want this for a private github project that I can invite you to if you want to test with that as well

**Comment by tdurieux** [comment]
Thank you for the example, I pushed a commit for this feature and it is now in production https://anonymous.4open.science/r/anonymous_github_test-59BE/video.md
