### ISSUE TITLE
files not found

### ISSUE THREAD

**Issue by Sofia-Kochkina** [tdurieux/anonymous_github#205]
Hi, I'm new to github, and I've managed to anonymize my repository. My issue is that while some files can be correctly viewed in the anonymous repository, some other files are "not found". I can clearly see all my files in original repository on github, and I use the link to my latest commit, so I was wondering what seems to be the issue.
![git_q](https://user-images.githubusercontent.com/109145384/235720448-ead6ba31-9e66-4d0b-a086-3f16af586784.png)

**Comment by tdurieux** [comment]
Thank you @Sofia-Kochkina for the bug report. I fixed the bug and the fix should be live in 1 minute.

**Comment by Sofia-Kochkina** [comment]
@tdurieux , thank you! It all works for me now!
