### ISSUE TITLE
regex does not seem to work as the "user=" field is not anonymized

### ISSUE THREAD

**Issue by FelixBenning** [tdurieux/anonymous_github#206]
Hi there. In my notebook I have a line `connect(; user="felixbenning")` (https://anonymous.4open.science/r/IncrementalGRF/notebooks/random_function_descent.jl line 229) and the regex "felixbenning" does not seem to work. I also tried to put the entire line there. This might have to do with the fact that I put the regex there after I first created the repository. But it should work right?

**Comment by FelixBenning** [comment]
It seems to have updated now, now it displays:

"Unable to download the file, check your connection or contact the admin."

when I click on the "view raw" link, I get a correctly anonymized version

**Comment by tdurieux** [comment]
Cloudflare has changed something in their configuration and if I don't specify the content type it can lead to this error message. I have no clue why. 

Anyway, it should be fixed now.
