### ISSUE TITLE
CORS header

### ISSUE THREAD

**Issue by Maximvdw** [tdurieux/anonymous_github#209]
Hey,

I have a use case where I have anonymised semantic data online on anonymous github (text/turtle , application/rdf+xml).
For a paper I want to access this resource via a web application (using the anonymous url). However, because there is no Access-Control-Allow-Origin header this is not possible.

Cors proxies is a bit messy because I do not access the URL directly, so I was wondering if it is possible to enable CORS?

Best,
Maxim

**Comment by tdurieux** [comment]
Hello,

I am a bit worried that the service could be abused. I need to think about it. 
An option would be to enable it for specific user.

**Comment by Maximvdw** [comment]
What about an opt-in per file? More work for you of course to design the UI, but also for people who want to abuse it.
