### ISSUE TITLE
The repository that you try to access is empty or is not accessible.

### ISSUE THREAD

**Issue by jeroenbe** [tdurieux/anonymous_github#21]
While initially the anonymisation worked, I can't seem to access the repository for a second time. What am I doing wrong? 

EDIT: it seems sometimes I get referred to the `empty.html` page, and sometimes I don't. I have a hard time figuring out what pattern causes this behaviour, sorry I can not be more specific than this.

**Comment by tdurieux** [comment]
THat is a strange behavior. Would it be possible to send me the repository by email? 

Thanks

**Comment by pphilippos** [comment]
Same here. I think it happened after a git push.

**Comment by cyclingProfessor** [comment]
It happened to me.  On a new repo with just one push

**Comment by tdurieux** [comment]
It is related to my GitHub API quota. I need to find a solution to reduce the API usage. I probably need to completely rewrite the service.

**Comment by root-intruder** [comment]
also happened to me today on a new repo with one commit...maybe think about a more detailed error message?!

**Comment by tdurieux** [comment]
> also happened to me today on a new repo with one commit...maybe think about a more detailed error message?!

@root-intruder Pull requests are welcome...

**Comment by root-intruder** [comment]
is there any workaround known?

**Comment by root-intruder** [comment]
OK I've found my issue...since the **master branch recently became disregarded, the branch name official is the new master**, however, the tool searches for master...so make sure you have a master branch!

I'll see if I can fix this and make a pull request
