### ISSUE TITLE
Anonymization stuck at preparation, cannot even remove it

### ISSUE THREAD

**Issue by azhe825** [tdurieux/anonymous_github#210]
This repo https://anonymous.4open.science/r/ContextualFairnessTesting-2B8C is stuck at preparation for days, cannot even remove it. Possible reason is that I changed the repo name of the original repo on GitHub. Is there anyway to fix it? Even remove it is fine so that I can use the same id for a new anonymous repo.

Thank you!

**Comment by tdurieux** [comment]
I fixed it manually, I am not sure what happened.
