### ISSUE TITLE
the updated contents on github did not show up in the anonymized version

### ISSUE THREAD

**Issue by anjuanand98** [tdurieux/anonymous_github#213]
I tried using force update as well, it did not work.

**Comment by tdurieux** [comment]
Could you give me the link to your repo?

**Comment by tdurieux** [comment]
You can send it by email, my email is on my GitHub profile.

Best

Thomas

On Aug 1, 2023 19:58, belisards ***@***.***> wrote:

I got the same problem, but I can't publish my repo now. Is there an alternative way to inform you about the anonymized URL?
