### ISSUE TITLE
Should not need full access...only read

### ISSUE THREAD

**Issue by dhakehurst** [tdurieux/anonymous_github#216]
Hi,
Trying to use this.
Looking for a file
in the anonymised repo 
but it does not exist!

![image](https://github.com/tdurieux/anonymous_github/assets/5618533/9a9dcd34-62c7-41a9-b564-5b4a76010bab)

Also, I now revoked access, due to the above,
you should only need read access...not full access which seems risky.

**Comment by dhakehurst** [comment]
PS.
I want to use this for a repo that I need to submit paper for on friday.
So if not fixed before then...I can't use your app. :(

**Comment by dhakehurst** [comment]
wierd!
now it is visible...

but there is still the access rights issue.

**Comment by tdurieux** [comment]
Unfortunately you are asking for something that does not exist. Read only is not an option on GitHub.

**Comment by dhakehurst** [comment]
its a public git repo...you need nothing in order to access the repo !!
