### ISSUE TITLE
Cannot anonymize/update repository

### ISSUE THREAD

**Issue by hihey54** [tdurieux/anonymous_github#217]
Hello, for some reason I cannot update nor anonymise any repository. Whenever I attempt an update (or an anonymisation of a new repo), everything begins but gets stuck at "preparing". 
(It is also extremely slow to "fetch" the information from a new repo)

This also affects repositories with just a readme; my quotas are barely used.

(For the record, I have been using this tool for ~1 year and this is the first time I had a similar issue)

**Comment by hihey54** [comment]
To provide a link to a (non-functional) repo: https://anonymous.4open.science/r/chinaphish-1C2D

**Comment by chaejin98330** [comment]
I am having the same issue..

**Comment by hihey54** [comment]
...for some reason, now everything is working :)

**Comment by chaejin98330** [comment]
Thank you for your reply!!!
