### ISSUE TITLE
Processed directory folder

### ISSUE THREAD

**Issue by balexx2** [tdurieux/anonymous_github#218]
when i run with .gen_all.sh, the processed directory folder is left empty. iam trying to figure out what could be the issue. Some assistance pliz. Thanks.

**Comment by tdurieux** [comment]
which gen_all.sh scrip?

**Comment by balexx2** [comment]
when i run flow_datasets.py file in the Neural bipartite matching, i get this error: i have tried to resolve it but until now i have failed.some assistance pliz. Plus how can support this page in terms of donation, can it accept visa card payment.
  File ~/ns-allinone-3.38/ns-3.38/km/flow_datasets.py:209
    f = SingleIterationDataset('./all_iter', split='test', less_wired=True, device='cpu', probp=3, probq=4)

TypeError: Can't instantiate abstract class SingleIterationDataset with abstract method len

**Comment by balexx2** [comment]
Additionally can i jointly workout a related project with you. i want to include DRL to Neural biapartite matching folder files.DRL for decison making based on maximum flows.In this case you being my guide. of course your help facilitated.Kindly let me know if you are available.Thanks

**Comment by tdurieux** [comment]
This is the repository of anonymous_github, you should contact the author of the paper not me.

**Comment by balexx2** [comment]
Additionally can i jointly workout a related project with you. i want to integrate DRL with ideas from Neural bipartite matching folder considering maximum flow as input. 
DRL for decision making. Can you be available as my guide. Of course your help facilitated.Kindly let me know if you are available.Thanks
