### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by JSybrandt** [tdurieux/anonymous_github#22]
http://anonymous.4open.science/ 

Current webpage is:

```
Welcome to nginx!
If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx.
```

**Comment by tdurieux** [comment]
Hello @JSybrandt,

It sometimes happens that the redirection is not made between http to https, I dont succeed to find the reason for that.
But the website is still running, on HTTPS.
