### ISSUE TITLE
Images are not showing up

### ISSUE THREAD

**Issue by mallcong** [tdurieux/anonymous_github#23]
Hi! 

First of all, thank you for developing this platform! This is so useful for paper submission!

I had an issue for opening a image file (*.png, *.jpeg) as shown on the snapshot below
![2](https://user-images.githubusercontent.com/3894400/62084188-b5328880-b226-11e9-9af2-8930b7727c88.JPG)
Those images are showing up on my repo but the anon repo. Is this only happening to me? 
Could you help me to fix this?
Thank you!

**Comment by tdurieux** [comment]
Thanks @mallcong for the feedback, could you send me the link to your anonymized repository?

**Comment by mallcong** [comment]
Hi Thomas,

My bad that I didn't realize that I could reply to this email so hope this
finds you well!
Here I attached my anonymous repo link.
https://anonymous.4open.science/repository/a63421a5-ad9f-459a-b3af-81e515b0ef2c/Appendix_A

Thank you so much for support!
Yun

**Comment by tdurieux** [comment]
Sorry for the late answer, I fixed the problem and now it is working!

**Comment by mallcong** [comment]
Thank you!

**Comment by NicolaiRuckel** [comment]
I have the same problem with svgs. I tried three different ways to specify the image path.

Here is a sample repository:
https://anonymous.4open.science/r/2df26dc2-6701-4318-9221-1b86900878f0/

You can find the non-anonymized repository here:
https://github.com/NicolaiRuckel/anonymous-test
