### ISSUE TITLE
"Internal Server Error" in https://anonymous.4open.science/github/login

### ISSUE THREAD

**Issue by xuanluolena** [tdurieux/anonymous_github#230]
To whom it may concern,

The login page shows internal server error. Also, receive "Errors" for the example repo: https://anonymous.4open.science/r/840c8c57-3c32-451e-bf12-0e20be300389/. Please kindly fix the issue.

Thanks!

**Comment by onefanwu** [comment]
I had the same problem! I hope @tdurieux can get the site back to normal soon.

**Comment by xuanluolena** [comment]
The issue has been fixed. Thank you to the anonymous team!

**Comment by Faizatahir305** [comment]
Hi, I am getting the same error.
