### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by shixiao9941** [tdurieux/anonymous_github#232]
Hi Anonymous GitHub author,

It seems there is something wrong with the server, as I encountered "Internal Server Error" when I tried to check my anonymous GitHub and log in. Also, the example GitHub repo (https://anonymous.4open.science/r/840c8c57-3c32-451e-bf12-0e20be300389/) on the home page of Anonymous GitHub couldn't access either. Could you fix this? I really appreciate it!

Thanks,
Xiao

**Comment by QinHsiu** [comment]
I have the same problem.

**Comment by fanourakis** [comment]
I have the same problem.

**Comment by RonnieFu** [comment]
I have the same problem

**Comment by pppppkun** [comment]
Will this issue have a negative impact on the peer review process?

**Comment by Mandeep-Rathee** [comment]
I am also facing similar issue.

**Comment by xiao910888** [comment]
I have the same problem, please let me know if it is solved

**Comment by JP-25** [comment]
I have the same problem, please let me know if it is solved

**Comment by pppppkun** [comment]
> Hi Anonymous GitHub author,
> 
> It seems there is something wrong with the server, as I encountered "Internal Server Error" when I tried to check my anonymous GitHub and log in. Also, the example GitHub repo (https://anonymous.4open.science/r/840c8c57-3c32-451e-bf12-0e20be300389/) on the home page of Anonymous GitHub couldn't access either. Could you fix this? I really appreciate it!
> 
> Thanks, Xiao

I find that the problem have been fixed, please check it.

**Comment by tdurieux** [comment]
My server was out of disk space. It is fixed now
