### ISSUE TITLE
textual formats listing in the FAQ is empty

### ISSUE THREAD

**Issue by rlhjansen** [tdurieux/anonymous_github#234]
Hi, on https://anonymous.4open.science/faq#formats as part of the FAQ there's a sentence which seems incomplete:

Anonymous Github considers the following file format as textual:

And then it just stops.

**Comment by tdurieux** [comment]
I will fix this but now anonymous GitHub analyzes the files to know if it is binary or textual and does not rely on a list of permitted extensions.
If it is textual it is anonymized otherwise it is blocked (if it is not an image or pdf).
