### ISSUE TITLE
Bug: Terms to anonymise folders do not update

### ISSUE THREAD

**Issue by zumatt** [tdurieux/anonymous_github#238]
The terms to anonymise in subfolders will be anonymised only with the words present in the first save.
If you update the repository with other terms, the files included in subfolders will not be updated.

**Comment by zumatt** [comment]
I cleaned my browser cache but if I modify something it will not be modified in subpages.
But I saw that the code is effectively modified in the anonimised repository.

Isn't it possible that there is a cache at the server level?
I am sure that my local cache is completely free (I have also tried with other browsers and/or private browsing)

**Comment by tdurieux** [comment]
Could you send me the repo ?

**Comment by zumatt** [comment]
I sent you a private message.

**Comment by zumatt** [comment]
Here the repo link: https://anonymous.4open.science/r/AIMLToolsTaxonomyFramework/

**Comment by tdurieux** [comment]
I don't succeed in reproducing which term is not anonymized for example?

**Comment by zumatt** [comment]
Now everything seems to be correctly updated.
I had to force update the repository anyway.
But 1 hour ago the links inside the subpage https://anonymous.4open.science/w/AIMLToolsTaxonomyFramework/toolsviz/ at the bottom right corner were not anonymized.
