### ISSUE TITLE
Readme not appearing as one of the files

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [tdurieux/anonymous_github#239]
Hi, when I create or view a repo, it says `README of pseudo-rnd-thoughts/temporal-explanations-4-drl was not found.` even though it does have a `readme.md`.
Is the backend crashing for some reason which is why this is happening? 

Mark

**Comment by tdurieux** [comment]
GitHub does not seem to find the readme either. can you double check that you pushed your readme?

**Comment by pseudo-rnd-thoughts** [comment]
Super strange, yeah, when look at Github then `readme.md` exists and is shown on the landing page of the project.
I have added you as collaborator such that you can spot anything that I'm missing

**Comment by tdurieux** [comment]
It is working now
