### ISSUE TITLE
Repo does not update when anonymization terms are edited

### ISSUE THREAD

**Issue by tilman151** [tdurieux/anonymous_github#240]
First of all, thank you for your work. It helps me a lot but I had the following issue:

When I created a repository, I tried to edit the anonymization terms afterward. After clicking the update button and waiting a bit, the repository did not update itself. I had to delete the repository and start anew.

**Comment by tdurieux** [comment]
It is updated, it is a question of cache.

**Comment by tilman151** [comment]
Thx, will check after emptying cache
