### ISSUE TITLE
Repository stuck at "Preparing"

### ISSUE THREAD

**Issue by xxx08796** [tdurieux/anonymous_github#242]
Hello:
After I edited the readme file and uploaded a few new files, the status of my anonymous repository is consistently showing as "preparing", lasting for nearly two days.
Can you help me to resolve this issue? It is quite urgent.

Thanks!

**Comment by tdurieux** [comment]
Your GPS repository is now ready.

**Comment by xxx08796** [comment]
thanks for your help!
