### ISSUE TITLE
Others can still find out the original repo based on the domain name?

### ISSUE THREAD

**Issue by Guptajakala** [tdurieux/anonymous_github#244]
Hi, I've added my repo on anonymous github and it gives me a url like this:
`https://anonymous.4open.science/w/coolrepo-XXXX/`

The repo is a github page. And if people search `coolrepo` on gitub, they can find out the original repo.  Is there any way to avoid this?

**Comment by tdurieux** [comment]
you can choose your own URL, you can choose a different one.

**Comment by Guptajakala** [comment]
@tdurieux , where can I set a different URL?

**Comment by tdurieux** [comment]
when you anonymize the repo
