### ISSUE TITLE
Project with CARLA 0.9.9.4 and Client 0.9.12 not work

### ISSUE THREAD

**Issue by frank-zzm** [tdurieux/anonymous_github#247]
Environment:
1. Carla 0.9.9.4 version and not recompiled from source code
2. python 3.7.0
3. client in windows, carla server in ubuntu20.04

**issue** log when running "runnable_template.py":
**WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 0.9.12 
WARNING: Simulator API version  = baf43b07 
A s s e r t i o n   f a i l e d :   G e t W i d t h ( )   *   G e t H e i g h t ( )   = =   S u p e r : : s i z e ( ) ,   f i l e   C : \ w o r k s p a c e \ c a r l a \ L i b C a r l a \ c m a k e \ . . \ s o u r c e \ c a r l a / s e n s o r / d a t a / I m a g e T m p l . h ,   l i n e   3 2** 

please help me about this issue, i do not know how to resolve this blockpoint

**Comment by tdurieux** [comment]
Please contact the author of the paper.
