### ISSUE TITLE
Remove Name from License

### ISSUE THREAD

**Issue by jcoreyes** [tdurieux/anonymous_github#25]
The current version does not anonymize names in a license file if it's included in the repo.

**Comment by tdurieux** [comment]
You mean a file like this one: https://github.com/tdurieux/anonymous_github/blob/master/LICENSE?

**Comment by jcoreyes** [comment]
Yes. I suppose it could also be up to the authors to remove it ahead of time but maybe it's a good option to have.

**Comment by tdurieux** [comment]
Thanks for the issue, I identified the problem and fix it.
Your name should now be anonymized is your License file.
