### ISSUE TITLE
Error: repo not accessible

### ISSUE THREAD

**Issue by Saauan** [tdurieux/anonymous_github#252]
Hello, yesterday I anonymized my repository, but I haven't been able to check it out on Anonymous GitHub as every time I go to the repository page, the following messages are displayed (not all at once, but in multiple visits) : 
"Anonymous GitHub is still processing the repository, it can take several minutes"
"Loading..." (Infamously long)
"ERRORS. The value of "offset" is out of range. It must be >=0 && <= 17825792. Received 17825795"
"ERRORS."
"Anonymous GitHub is unable to or is forbidden to access the repository."
Also, I had one more error messages concerning an API limit that was reached but I didn't save it.

So, it seems like my repository might be cursed. Is it like, too big or has too many files ?

**Comment by Saauan** [comment]
I have around a million of files ! I can see why that may be an issue though

**Comment by tdurieux** [comment]
This is the issue, weirdly enough it seems that it is Github API that is failing. Not sure how to solve that. AG does not handle well big repos
