### ISSUE TITLE
The anonymizes repo does not show updated file intermittently.

### ISSUE THREAD

**Issue by bhaveshneekhra** [tdurieux/anonymous_github#253]
We used anonymous.4open.science to anonymise our github repo for submission. When we submitted we could see all the files updated. 
Today morning when we checked we found the anonymous repo was reflecting older version, not the latest one.
I had to force update the repo once again.

We could see the updated files, but then we found our ReadMe.md was still the older version. 

It reflected the latest version after someime.

The only thing I changed in the settings was to uncheck "Auto-update". Is that an issue? 

Should auto-update be on? 

I do not want my anonymous repo to be updated after I have submitted the code for review? 

Let me know if I am doing something wrong.

**Comment by tdurieux** [comment]
It is related to the cache of your browser. It is not an issue for people that would visit your repo frequently.
