### ISSUE TITLE
image not rendered

### ISSUE THREAD

**Issue by bahruzjabiyev** [tdurieux/anonymous_github#259]
Hey, Thomas. 

I tried different formats for my image in README, but I could not get Anonymous Github render the image for me. Any idea how I can fix it?

https://anonymous.4open.science/r/gudifu-fuzzer-6FB8

**Comment by tdurieux** [comment]
hi @bahruzjabiyev , the issue is that you provided an absolute path, could you use `<img src="misc/gudifu-1.png">` instead of`<image src="/misc/gudifu-1.png">` ?

**Comment by bahruzjabiyev** [comment]
Thank you so much, Thomas. It worked. Have a nice day!
