### ISSUE TITLE
Login to GitHub - Internal Server Error

### ISSUE THREAD

**Issue by alkorang** [tdurieux/anonymous_github#26]
I can access the main page and already imported anonymous repositories. But when I try Login to GitHub, I get 500 Internal Server Error. URLs of error pages look like:
https://anonymous.4open.science/github/auth?code=ea2cc82711f7ed4bff46&state=QOM9Pqa26MoOCqEwausW7baMs5D6Lr
(The code and state part of URL change when I try to login again.)

**Comment by tdurieux** [comment]
Thanks for the feedback, I will look at this when I will have access to my computer

**Comment by tdurieux** [comment]
I really dont understand what is happening. 
When I put in place this service everything was working and now I have problem to connect even with my own account. It does not make sense.

**Comment by tdurieux** [comment]
It is working again :/ so strange.

**Comment by alkorang** [comment]
> It is working again :/ so strange.

Now it's working with my account, too! :)
