### ISSUE TITLE
Link broken with original repo, can't exipre anonymous github

### ISSUE THREAD

**Issue by Javaria-Ahmad** [tdurieux/anonymous_github#260]
I wanted to expire my anonymous link but by mistake I made the original github repo private first. That broke the link between the original repo and the anonymous link. I am unable to expire the link now and it shows the data posted previously. Could you please help me with expiring the anonymous link. Thank you.

**Comment by tdurieux** [comment]
You can remove your repository. It will have the same effect as expiring it.

**Comment by Javaria-Ahmad** [comment]
This is the issue. Looks like all control over the anonymized repo is gone
from the dashboard. I do not even see it under the dashboard. Is there
another way to remove the anonymized repo?

**Comment by tdurieux** [comment]
it is still there, just change the filters

**Comment by Javaria-Ahmad** [comment]
Thank you, that worked.
