### ISSUE TITLE
Error when getting repository information

### ISSUE THREAD

**Issue by XuRuihan** [tdurieux/anonymous_github#264]
I ran into bugs when I was using anonymous_github. The only log is at the right bottom of the page:

```
Error when getting repository information

XuRuihan/Anonymous produice the following error: Cannot read properties of undefined (reading 'repoId')
```

![image](https://github.com/tdurieux/anonymous_github/assets/50470253/476d9dd0-6a76-4718-a6f1-8415b8a6ce84)

I can do nothing as nearly all manage buttons have no response. No actions, no new anonymous repository, no remove.
Please HELP ME! 😭😭😭

**Comment by tdurieux** [comment]
Your repo is not accessible
