### ISSUE TITLE
[URGENT]update repository failed

### ISSUE THREAD

**Issue by hidingmyname** [tdurieux/anonymous_github#266]
My anonymized repository is unable to show.

on dashboard:
Error : repo_not_accessible

when refreshed:
Anonymous GitHub is unable to or is forbidden to access the repository.

upon navigating into repository from dashboard:
Anonymous GitHub is still processing the repository, it can take several minutes.

**Comment by hidingmyname** [comment]
I want to keep my previous repository link too.

**Comment by hidingmyname** [comment]
Or can I change the Anonymize repository id back to the number of previous ID?

**Comment by hidingmyname** [comment]
The website show "Anonymous GitHub is still processing the repository, it can take several minutes." And I check this issue [https://github.com/tdurieux/anonymous_github/issues/252](url). My repository contains about 7,000 files (less than ten thousand). How should I fix this anonymous repository. It is really urgent.

**Comment by tdurieux** [comment]
The repository is accessible. I consider the problem solved
