### ISSUE TITLE
Question: Jekyll support for GitHub Pages

### ISSUE THREAD

**Issue by joel-coffman** [tdurieux/anonymous_github#269]
Does Anonymous GitHub support the use of Jekyll comparably to GitHub Pages, specifically the conversion of Markdown files in, say, the `docs` directory into a static website that is anonymous?

**Comment by tdurieux** [comment]
I do convert markdown files to `html` (without any formatting) but I do not support `Jekyll`. I do not know enough about Jekyll to know if I would be able to support it.
(each file needs to be able to be converted on the fly individually)

**Comment by tdurieux** [comment]
After looking at the doc, it does not seem I will be able to support this feature anytime soon sorry

**Comment by joel-coffman** [comment]
Thank you for your response, @tdurieux!

> I do convert markdown files to html (without any formatting) but I do not support Jekyll.

May I suggest that a statement to this effect be added to the existing documentation? If you're amenable to this suggestion, would you like me to create a pull request to that effect?

> After looking at the doc, it does not seem I will be able to support this feature anytime soon sorry

No worries! It sounds like the best workaround -- for anyone who wants to use Jekyll -- is to build locally and commit the generated site to the repository in which case the HTML, CSS, etc. would be viewable yet anonymized, correct? (I'm mostly documenting this idea in case someone else stumbles upon this issue at some point.)

**Comment by tdurieux** [comment]
PRs are more than welcome. Pure HTML or MD is working fine. I agree that it could also be documented.
