### ISSUE TITLE
500 Internal Server Error when submitting the creation form 

### ISSUE THREAD

**Issue by fabiocapsouza** [tdurieux/anonymous_github#28]
I am trying to anonymize a repository but I keep getting 500 Internal Server Errors.

Repository URL: https://github.com/neuralmind-ai/portuguese-bert
Terms:
```
neuralmind
fabio
souza
rodrigo
nogueira
roberto
lotufo
1909.10649
```
Expiration options: Redirect to GitHub repository
Expiration date: 25/02/2020

Generated link with error: https://anonymous.4open.science/r/ac885bb6-1bd0-400f-9587-f9121d8a83b4/

The repository does not contain code, it has a readme and a pdf file. I suspected it could be that one of the terms appears at the repository url, but the error happens even without any terms.

**Comment by fabiocapsouza** [comment]
After many retries, I could create a first anonymized link and then edit to include the desired the terms. However, I could not set an expiration date, so I believe the error is related to it.

**Comment by tdurieux** [comment]
Hi,

Sorry for the delay, there is indeed an issue with the expiration date. I did not succeed to identify the reason for the moment.
I will investigate. Thanks

**Comment by tdurieux** [comment]
I just found the bug, thanks for the issue
