### ISSUE TITLE
The requested file is not found.

### ISSUE THREAD

**Issue by chenyushuo** [tdurieux/anonymous_github#281]
I have an anonymous github repository but it can not display proper content.
![image](https://github.com/tdurieux/anonymous_github/assets/31039063/f21ffa44-236a-4705-820c-897dfeae53f5)
![image](https://github.com/tdurieux/anonymous_github/assets/31039063/d7cd6e47-7e02-43fa-8aac-49d68d56ac92)

**Comment by tdurieux** [comment]
Fixed
