### ISSUE TITLE
website {"error":"file_not_found"}

### ISSUE THREAD

**Issue by PaLLaMAVC** [tdurieux/anonymous_github#282]
The repo configuration is normal, but the web page cannot be displayed.

[https://anonymous.4open.science/w/SECdemo/](https://anonymous.4open.science/w/SECdemo/)

**Comment by tdurieux** [comment]
It has been fixed this morning

**Comment by PaLLaMAVC** [comment]
> It has been fixed this morning

Thanks !  I have seen it
