### ISSUE TITLE
Folder content is duplicated everytime I click to expand the folder in the side menu

### ISSUE THREAD

**Issue by helenocampos** [tdurieux/anonymous_github#286]
When opening a repository page and clicking on a folder in the side menu, every time the folder is clicked, its items are duplicated.
The problem was found using a repository hosted in the public instance (https://anonymous.4open.science/)

https://github.com/tdurieux/anonymous_github/assets/5610771/9b4cdfba-9d1a-48e6-b178-5f514803e49e

**Comment by tdurieux** [comment]
I would need the repo to fix this case.

**Comment by helenocampos** [comment]
Sorry, I can't really share this repo yet, since this could give me out in a double blind-reviewing process.
I just found this example repository through Google, where the problem also happens: https://anonymous.4open.science/r/840c8c57-3c32-451e-bf12-0e20be300389

**Comment by tdurieux** [comment]
I do not have a problem on that repository. could you force refresh and try again in your repo?

**Comment by helenocampos** [comment]
Did you try to click on a directory more than once, like in the video?
What kind of info do you need? 
I'm not used to TypeScript, but I realized that every time I click a directory in the directory tree, a call is made to the API to retrieve its content. The problem may be around there in the code. 
![image](https://github.com/tdurieux/anonymous_github/assets/5610771/fba91fc1-6479-4abf-aca6-71d6e15e7cd8)
The content the API retrieves is correct, only one of each entry. However, all entries are appended to the already existing, causing the list to become repetitive.
![image](https://github.com/tdurieux/anonymous_github/assets/5610771/98b721b6-f37b-44e1-9385-2870399be9da)
![image](https://github.com/tdurieux/anonymous_github/assets/5610771/e95daf2c-8ad1-4ad8-81df-69c9d1886756)

**Comment by tdurieux** [comment]
Fixed the issue
