### ISSUE TITLE
Downloading or Display large files

### ISSUE THREAD

**Issue by Gongxter** [tdurieux/anonymous_github#29]
Currently im having an issue in which the data i want to provide is too big to be shown. This leads to the following problem:

At the end of the File this is shown:

``...``
``<More data exists, we delete it to allow the preview>
``
the text file itself is less than 1 MB and withing Githubs requirements.

so my question is now if it is possible to somehow download the whole file or display the whole file.

**Comment by tdurieux** [comment]
It is technically possible but the issue is that it will break the double bind because the download URL will contain the identifier of the repository.
