### ISSUE TITLE
Some files are not shown in the navigation bar

### ISSUE THREAD

**Issue by mhellmeier** [tdurieux/anonymous_github#290]
I anonymized this repository:
https://github.com/FraunhoferISST/TREND
resulting in the following:
https://anonymous.4open.science/r/Kotlin-Example

If you navigate to the folder `watermarker/src/commonMain/kotlin` in the anonymized version, the folder seems to be empty:
https://anonymous.4open.science/r/Kotlin-Example/watermarker/src/commonMain/kotlin
The source repository shows different files and folders that are missing in the navigation bar of anonymous GitHub:
https://github.com/FraunhoferISST/TREND/tree/main/watermarker/src/commonMain/kotlin

I tried to visit a file directly via the URL, and it is available:
https://anonymous.4open.science/r/Kotlin-Example/watermarker/src/commonMain/kotlin/Watermarker.kt

Therefore, all files seem to be correctly cloned to anonymous GitHub, and the bug seems related to the navigation bar.

**Comment by tdurieux** [comment]
thank you for the bug report, it is now fixed
