### ISSUE TITLE
My Anonymous repository got expired. Can I recover it somehow?

### ISSUE THREAD

**Issue by Drishya21119** [tdurieux/anonymous_github#296]
I had created a repository, but now it shows it got expired! Is there a way maybe I can recover it back?

**Comment by tdurieux** [comment]
You can update it's configuration

**Comment by khannabeela** [comment]
@Drishya21119 Hi

Were you able to recover the repository?

**Comment by tdurieux** [comment]
@khannabeela you should just do the same and update your repo configuration.
