### ISSUE TITLE
Either the server is overloaded or there is an error in the application.

### ISSUE THREAD

**Issue by dlagul** [tdurieux/anonymous_github#31]
When I try to login to github for private repositories, I got the error message as follows:

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application

What are the causes of the problem and how to solve them?
Thanks very much.

**Comment by YH-learning** [comment]
I also got the problem, help.

**Comment by philipco** [comment]
Hello, I got the same error. I have a private repository that I anonymized. Now, I want to edit the repo, however I am redirected to an "Internal Server Error" page. What can I do ? 
Thanks for your help.
Best regards.

**Comment by tdurieux** [comment]
I am sorry, I was busy in the last days. I did not see your message. I am currently looking at the log of my server to try to understand what happened. 

Best,

**Comment by twangnh** [comment]
same problem

**Comment by tdurieux** [comment]
It is related to the authentification, the token is expired and I cannot contact GitHub anymore. I am still thinking how I can solve this problem.

**Comment by tdurieux** [comment]
Could you try to login again in anonymous github: https://anonymous.4open.science/github/login and then edit your repo?

**Comment by mateuszwilinski** [comment]
Still internal error. :(

**Comment by twangnh** [comment]
same problem

**Comment by tdurieux** [comment]
can someone send me the id of his repository by email?

**Comment by twangnh** [comment]
@tdurieux do you mean the github url of the repository? Now my problem is that I cannot even login to github by clicking the **Login to Github** Thanks!

**Comment by tdurieux** [comment]
@tdurieux I meant the id of the repo on https://anonymous.4open.science/, I changed something related to the login. Could you have a try?

**Comment by mateuszwilinski** [comment]
It works now, great job! Thank you very much.

**Comment by pradm007** [comment]
Hi, I am still facing the error.

**Comment by tdurieux** [comment]
@pradm007 your configuration is incorrect, you provided the link to your profile and not the link to a repository.

**Comment by pradm007** [comment]
@tdurieux Thank you for the response.
I initially tried with my repository direct path [ https://github.com/pradm007/TQMine ] but it says 'The repository that you try to access is empty or is not accessible.' while it is a public repository.

**Comment by tdurieux** [comment]
It is strange, the access token that is associated with your account seems to be expired which should normally never happen. Did you remove anonymous github from the list of authorized apps in your GitHub account?

**Comment by pradm007** [comment]
@tdurieux Yes, you are correct.
So initially I tried the anonymous process by putting the repository link and it gave the 'The repository that you try to access is empty or is not accessible.' error.

Then I tried to check if login-github works by granting the entire access and it did show me the list of all the repo links, (which is as expected) but I did not proceed to select a repo. I looked into the issue section and your comment said it was fixed a few hours back, so I revoked the auth-access and tried the anonymous process again following which I commented on the issue.

Please advise.

**Comment by tdurieux** [comment]
> So initially I tried the anonymous process by putting the repository link and it gave the 'The repository that you try to access is empty or is not accessible.' error.

Did you use the login button before this happens?

I normally fixed your configuration manually, it should work now

**Comment by pradm007** [comment]
@tdurieux No, I didn't. When it happened I thought the README.md file might not have been updated recently.
I tried now, it works. Thank you so much. This project is really good. :slightly_smiling_face: :thumbsup:

**Comment by ShwanMario** [comment]
Hi, thanks for your brilliant work. 

I got the same error when I tried to edit my anonymous repo, would you mind if I send you my repo id then you have a look at what's happening with that repo?

Regards.

**Comment by tdurieux** [comment]
Yes, please send me your id. But first, could you try to go to https://anonymous.4open.science/github/login and then do the edit?

**Comment by TiagoCortinhal** [comment]
Hey!

I tried both versions (URL and via login) and I cannot do it (either empty error or Internal Server Error).

**Comment by tdurieux** [comment]
it is really surprising. I don't handle the login by myself. I will have a deeper look.

**Comment by TiagoCortinhal** [comment]
I tried again after I commented and everything worked as expected.

**Comment by kayleejorose** [comment]
Hello, I am having a similar issue as described above. Though I'm able to view most of my repository and files, only certain files are giving me the Internal Server Error. I logged in using my GitHub login and it this app is authorized. Thank you for your time!

**Comment by kayleejorose** [comment]
I actually found the cause for the error I was getting! I will describe in case it is useful--I had a folder named 'R scripts' with the space in it (bad naming convention). This was the reason why the site could not access these files I believe. I pushed the changes removing the space and am now able to view these files.
