### ISSUE TITLE
"Anonymous GitHub is still processing the repository, it can take several minutes." does not go away

### ISSUE THREAD

**Issue by IljaSir** [tdurieux/anonymous_github#311]
After updating my git repository and enforcing an update at anonymous github, the update is still pending and I see the following message: "Anonymous GitHub is still processing the repository, it can take several minutes".
It lasts 2 days already.
How can I solve this problem?

**Comment by LZH-YS1998** [comment]
same problem, have you solved it yet？

**Comment by IljaSir** [comment]
@LZH-YS1998 After some time of waiting (a week or so) it solved itself.
