### ISSUE TITLE
Not all given terms are anonymized on website, but only in .zip

### ISSUE THREAD

**Issue by JetteReeg** [tdurieux/anonymous_github#323]
Hi,
I am wondering if there is a bug in the web interface. 
When I check the anonymization within the URL (firefox + microsoft edge), not all of the given terms are anonymized. However, they are anonymized correctly when I download the files.
E.g. [here](https://anonymous.4open.science/r/BiTZ-4178/README.md) 'Reeg_et_al_2022' is not anonymized in the web browser, but if I download the file and the same is true for [this file](https://anonymous.4open.science/r/BiTZ-4178/XXXX-1/README.txt) where 'Reeg' should have been anonymized but is only in the downloaded versions.
I can't see anything in the settings that could be causing this problem: 
![Screenshot 2024-09-09 130714](https://github.com/user-attachments/assets/bad14b01-2fb9-41bf-8ba7-217bcb2aa240)
Any help would be appreciated.

**Comment by tdurieux** [comment]
It is the same anonymization for both there should not be any difference.
It is due to your browser cache. the reviewers will not see it.
