### ISSUE TITLE
The file *.zip is too big to be anonymized (beyond 1MB, Github limit)

### ISSUE THREAD

**Issue by zorikg** [tdurieux/anonymous_github#33]
Hi,
Thanks for making this amazing tool available.
I used this tool to double-blind a repository for a paper submission. Unfortunately I did not found any mentions about a limit and now discovered that the reviewers cannot download the file.
My question is - is there any way I could allow larger files to be anonymized? Is there any subscription I can pay for to allow larger files? At this stage I cannot modify the URL.

Thanks!

**Comment by tdurieux** [comment]
Hi,
Unfortunately, it is a limitation of GitHub for the API that this project use.
Changing this would require to change drastically how the project work.
I will update the website to highlight the limitations.
