### ISSUE TITLE
Fine-grained access controls

### ISSUE THREAD

**Issue by JasonGross** [tdurieux/anonymous_github#337]
I'd like to use anonymous github without giving write access to all public and private repositories.  Can there be an authentication mode which requests only the minimal access (email address and username for authentication?), and one which asks for the additional minimal access for private repositories (read access only)?  (This is from clicking "log in" on https://anonymous.4open.science/)
<img width="538" alt="image" src="https://github.com/user-attachments/assets/6e532591-a439-4980-b0e9-ced8d804c6af">

**Comment by gdalle** [comment]
@tdurieux this has been the main barrier to me using your (awesome) service sofar. In particular, why do you need write access to anything at all?

**Comment by tdurieux** [comment]
Github does not allow to do it. Unfortunately there is nothing I can do.

**Comment by gdalle** [comment]
The best workaround I found is to create an organisation with only the repos I want to anonymize, so that I don't give write access to my entire GitHub account. Do you have any smarter suggestion?

**Comment by JasonGross** [comment]
I have used GitHub to log into many services without giving the service any access beyond name, email, profile photo, and maybe GitHub user name.  What is it that GitHub does not allow?

**Comment by tdurieux** [comment]
It is either getting access to your list of public repo or getting access to read and write to your private repo. It is not possible to have access to read only. Welcome to GitHub...

**Comment by gdalle** [comment]
Am I the only one to think it would be better to have read only access to the public repositories, and give up on the private ones? After all, if we use anonymous GitHub, we're putting the repo out there anyway

**Comment by JasonGross** [comment]
I would still very much like the option to authenticate giving only the list of public repos.  Can getting access to private repos be made optional?

**Comment by gdalle** [comment]
To be clear, this is not a criticism of your project, which is the only solution out there to a very important issue. I'm just trying to see if some barriers to use can be lifted
