### ISSUE TITLE
The site is broken - Unable to open the webpage 

### ISSUE THREAD

**Issue by LongchaoDa** [tdurieux/anonymous_github#352]
Hi,

I have tried to open the previously generated anonymous link, but it failed. 
Then I verified that, even for the site:
https://anonymous.4open.science/

I can not even login to the page successfully. 

Is the site broken? Would appreciate it if you could fix that since it is crucial for the review process.

[update]
Any previous generated link is invalid now

Best,

**Comment by Dodo-D-Caster** [comment]
same issue

**Comment by LongchaoDa** [comment]
> same issue

It is solved, Please check the link again
