### ISSUE TITLE
Why can't I get into the anonymous repository

### ISSUE THREAD

**Issue by zhao-chunyu** [tdurieux/anonymous_github#355]

**Comment by szzzy** [comment]
Same question. The error returned is "Connection timed out Error code 522" with "anonymous.4open.science Host Error"
It looks like there is a problem with the source server.
Please fix it quickly, I use an anonymous repository in my submitted paper. It is very important to me.

**Comment by szzzy** [comment]
Same question. The error returned is "Connection timed out Error code 522" with "anonymous.4open.science Host Error"
The Browser and Cloudflare all work well. It looks like there is a problem with the source server.

**Comment by Wzy-source** [comment]
same issue

**Comment by tdurieux** [comment]
My host service seems to be completely down. There is not much I can do. I hope it will come back to live. 
I do not have solution for the moment.
Wait and see

**Comment by conradborchers** [comment]
> My host service seems to be completely down. There is not much I can do. I hope it will come back to live. I do not have solution for the moment. Wait and see

Any updates on this?

**Comment by tdurieux** [comment]
It was up on Nov 2.

**Comment by conradborchers** [comment]
I had the same error earlier today, though.

On Dec 26, 2024, at 1:05 PM, Thomas Durieux ***@***.***> wrote:

﻿

It was up on Nov 2.
