### ISSUE TITLE
PDF unknown extension

### ISSUE THREAD

**Issue by 18goldr** [tdurieux/anonymous_github#39]
I would like to include a pdf in my repo, but it does not let me because it is supposedly not a valid extension... I don't need anything to be anonymized in it, I would just like it to be made available through the anonymous repo.

**Comment by tdurieux** [comment]
The issue is that I am not able to anonymize PDF. I don't know when it is safe or not to render it.

Any suggestion for handling this case is welcome.

**Comment by 18goldr** [comment]
My suggestion is to simply allow the option, but with the explicit notice and caveat that you can't anonymize it, so the pdf should be anonymized. You could also add an option to upload a tex file, anonymize that, then compile it to pdf, then delete the tex file.

**Comment by Bakkhos** [comment]
In the repository configuration, near where you enter the list of words to mask, one could provide an option to specify files that should be accessible regardless of anonymization. Maybe a text field to enter a path or a glob.
