### ISSUE TITLE
SERVER FAILURE!

### ISSUE THREAD

**Issue by tdurieux** [tdurieux/anonymous_github#44]
Hello,

Last night the server that was hosting the service has suffered a critical hardware problem.
It is currently not clear how much data is lost. The service will be unavailable until further notice.

I am sorry for the inconvenience. I, unfortunately, cannot do much.

**Comment by tdurieux** [comment]
Unfortunately, the data of the last month has been lost. I did not find a solution to recover the lost data.
if you want to restore your repository, you can anonymize your repository again and the link to the repository and the old id. I will update the server to restore the old id.

**Comment by 2165998** [comment]
Oh,my page is 404. I have add the link in  my submitted paper (waiting for review). How to recover the content in that link?

**Comment by tdurieux** [comment]
Anonymize your repository again and send me your old link and new link. I will update the server to recover your content.

**Comment by 2165998** [comment]
> Anonymize your repository again and send me your old link and new link. I will update the server to recover your content.

Hi, I have send my old link and new link to your email(thomas@durieux.me).

**Comment by nslay** [comment]
My repository was unaffected, but it has a slightly different filter. Could this explain one of the missing filter terms? Otherwise, I thought a reviewer might have violated the rules and modified my filter.

**Comment by tdurieux** [comment]
Yes it is possible, the server has been restored with last month data. Therefore if you updated the terms, the old terms will be used.

**Comment by AjeyPaiK** [comment]
Hi, 

We submitted a paper and waiting for the reviews. However, the anonymous link is now 404. Is there a way to restore the repo at the same link?

HELP!!! URGENT!!!

**Comment by AjeyPaiK** [comment]
> Hi,
> 
> We submitted a paper and waiting for the reviews. However, the anonymous link is now 404. Is there a way to restore the repo at the same link?
> 
> HELP!!! URGENT!!!

Thank you Thomas for promptly helping us restore the link.

**Comment by zdh2292390** [comment]
> Anonymize your repository again and send me your old link and new link. I will update the server to recover your content.

Hi, Thomas
I also have the same problem of the 404 error. I have sent my old link and new link to your email (thomas@durieux.me). Could you help recover it? It would be greatly appreciated! 
Thanks in advance.

**Comment by smallGum** [comment]
Hi, I have also sent my old link and new link to your email (thomas@durieux.me). Please help me to restore the old link.
Thanks very much!

**Comment by tdurieux** [comment]
I restored your previous links.

**Comment by smallGum** [comment]
> I restored your previous links.

Yes, thank you for handling it so promptly!

**Comment by susheels** [comment]
I have sent you an email with both the old and new links. Please help me restore the old link. Thanks!

**Comment by jqyin** [comment]
Hi Thomas, 
I too have sent you an email with both old and new links. Please kindly help me to restore the old links.
Thanks so much!

**Comment by Ravenclawoo** [comment]
Hello Thomas, I have met the same problem. I submitted two papers. I have already e-mailed you both of the old link and new link of my two projects. Hope you can help me restore the old links. Thanks in advance.

Best regards,
Haolun

**Comment by Daftstone** [comment]
Hello Thomas,
The codes of the two papers I hosted are both 404. I have emailed you the old and new links of the two papers. Can you help me recover them? Thank you!
Best wishes!

**Comment by cuilakers** [comment]
Hi, I have send my old link and new link from my email(lakers@mail.ustc.edu.cn) to your email(thomas@durieux.me). Please help me restore the old anonymous link！URGENT!!! Thanks very much!

**Comment by HaraldMelin** [comment]
Hi Thomas, 
I have also encountered this issue for the repos of two papers. I emailed you old and new links, please help me restore them. Thank you in advance!
Best regards,
Harald

**Comment by TrafficPredictviaTraj** [comment]
Hi Thomas,

My old link is also encountering a 404 error. 
The link is in a being reviewed research paper.
I have sent both my old link and a new link to your email (thomas@durieux.me)).
I would be most thankful if you could help me restore my link.

Best regard,
Bo

**Comment by JuliaHerbinger** [comment]
Hi Thomas,

I had the same issue as everyone here. 
I also sent you an email with the old and new link. Would be really gread if you are able to restore the link :)

Best wishes,
Julia

**Comment by tdurieux** [comment]
The new version of Anonymous Github has been deployed. With this new version you can choose the anonymized id, therefore you can restore the link by yourself.

Sorry again for this problem.
