### ISSUE TITLE
Logo Suggestion

### ISSUE THREAD

**Issue by tdurieux** [tdurieux/anonymous_github#46]
Hi all,

It would be nice to have a logo for anonymous github but I don't have good ideas.

Do you have suggestions?

**Comment by server-python** [comment]
Hello:)
i.am server Python:)
I am talking to the translator now :)
I know Python programming, but there are still several libraries left
I want to be a member of Anonymous :D
As you can see my GitHub logo looks like Anonymous :)))))))))))))))))))))))
Guide me :)

**Comment by server-python** [comment]
I have a picture :)

**Comment by server-python** [comment]
![000](https://user-images.githubusercontent.com/110650714/183328648-9ed0e67d-502c-47f4-86b7-18e484a5d6e0.png)

**Comment by server-python** [comment]
it is so beautiful :)
