### ISSUE TITLE
Meet 404 Error after creating an anonymous repo two months ago

### ISSUE THREAD

**Issue by geekinglcq** [tdurieux/anonymous_github#48]
Hi there, thx for provide this awesome tool firstly. 
I have used it in the submission of a paper for KDD about two months ago. However, recently I meet the 404 error when I try to check it with the [generated url](https://anonymous.4open.science/r/f44f849f-0537-4f09-a2c0-624bef73c351/). Could you please help me check it?

**Comment by tdurieux** [comment]
Hello,

Please follow the instructions in #44
