### ISSUE TITLE
add support for removing an anonymized repository

### ISSUE THREAD

**Issue by monperrus** [tdurieux/anonymous_github#5]

**Comment by CoryParsnipson** [comment]
I came here hoping to request this feature, especially if it could expire after a specified certain amount of time, as monperrus stated in issue #6.

I have this use case in mind, where I need to submit a repo to a committee for review, but I don't want them to be able to go back at any time and google search the repo text and find me. (This won't help if they decide to make a copy of the provided repo, but that's good enough for me.)

This is really great stuff, btw. Keep up the good work!

**Comment by tdurieux** [comment]
Hi @CoryParsnipson,

I added this option today, you can now set up an expiration date. At the expiration date, you can either remove the repository (It is not really removed it is marked as unavailable) or you can redirect to the github repository (useful after publication).

Thomas

**Comment by CoryParsnipson** [comment]
Thanks so much! I will test it out soon. 👍

**Comment by tdurieux** [comment]
Btw, you can update your existing repositories.
