### ISSUE TITLE
Can't open the main page 502 Bad Gateway

### ISSUE THREAD

**Issue by bhavyaghai** [tdurieux/anonymous_github#51]
Hi,
    I am getting Error 502 bad gateway on opening the main page i.e. https://anonymous.4open.science/.  Also, all my anonymized repo links are down. Is the server down or is something wrong going on my end?  If its something wrong with the server, when can we expect it to get it fixed?

**Comment by joonsung90** [comment]
Hi.
I am also suffering from the same problem. I can't access my all anonymized repositories. When it will be fixed?

Thanks.

**Comment by tdurieux** [comment]
I had a problem with my server. I restarted it. It is now working properly and the problem will not happen again.

**Comment by joonsung90** [comment]
Hi. @tdurieux 
It doesn't work again. :(
If you don't mind, could you let me know why the host server is down? Is it a transient issue or not? As I am using this anonymous repository for the paper currently reviewed, if the problem cannot be fixed in a short time, I need to find another option and contact the editor.

Always thanks for your support.
Thanks.

**Comment by claytoncohn** [comment]
Same issue again today: 502 bad gateway.

**Comment by SiamakGhodsi** [comment]
Same problem today for me: 
Bad gateway Error code 502

<img width="2005" height="1307" alt="Image" src="https://github.com/user-attachments/assets/093719b3-45c2-4cd1-9bb1-857c8fdd5082" />

**Comment by lucala** [comment]
@tdurieux I love anonymous.4open.science, but this error keeps happening unfortunately. Is there a way we can resolve this permanently? It would be very sad if this happens when reviewers are trying to look at our demo pages... It will make everyone look bad 😢

**Comment by guijinxin** [comment]
> [@tdurieux](https://github.com/tdurieux) I love anonymous.4open.science, but this error keeps happening unfortunately. Is there a way we can resolve this permanently? It would be very sad if this happens when reviewers are trying to look at our demo pages... It will make everyone look bad 😢

I meet the same issue, is there any solution?
