### ISSUE TITLE
Can't open the main page 502 Bad Gateway (Reopen)

### ISSUE THREAD

**Issue by joonsung90** [tdurieux/anonymous_github#52]
Hi.

Quote the previous issue
_Originally posted by @tdurieux in https://github.com/tdurieux/anonymous_github/issues/51#issuecomment-826521610_

The host doesn't work again. :(

If you don't mind, could you let me know why the host server is down? Is it a transient issue or not? As I am using this anonymous repository for the paper currently reviewed, if the problem cannot be fixed in a short time, I need to find another option and contact the editor.

Always thanks for your support.
Thanks.

**Comment by tdurieux** [comment]
In this case, it was a race condition bug. I fix the bug and restarted the server.

I was hoping to avoid this by having a beta open for more than one month but nobody tried it... There is a limit of what a single person can do and test.

With time the number of bugs will decrease :)
