### ISSUE TITLE
Some file content gives 500s

### ISSUE THREAD

**Issue by micahjsmith** [tdurieux/anonymous_github#55]
For example, I am seeing a 500 on this page: https://anonymous.4open.science/r/75e9ad20-7882-414e-a522-254844f1d77e/README.md

![image](https://user-images.githubusercontent.com/5473606/116704236-2faeb000-a999-11eb-913a-c89554a6a962.png)

In the dev console:
```
XHR GET https://anonymous.4open.science/api/repo/75e9ad20-7882-414e-a522-254844f1d77e/file/README.md
[HTTP/2 500 Internal Server Error 158ms]
```

**Comment by tdurieux** [comment]
Fixed

**Comment by micahjsmith** [comment]
thank you!
