### ISSUE TITLE
What are GitHub write permissions required for?

### ISSUE THREAD

**Issue by henrikplate** [tdurieux/anonymous_github#56]
Dear @tdurieux ,

First of all thank you for this solution, great idea and work!

I noticed that the app requires write permissions for my repos, and I wondered where and why this is actually required. Can you shed some light on this please? I believe requiring just read-only permissions would convince even more people to use Anonymous GitHub.

Cheers, Henrik

**Comment by tdurieux** [comment]
Dear @henrikplate,

I don't need write access to the repository, only read access. However, I did not find a permission scope [1] that allows accessing private repositories in read-only. If you know how to do that I will be happy to change the scope. For now, I don't know what I can do about it. 

[1] https://docs.github.com/en/developers/apps/scopes-for-oauth-apps

**Comment by henrikplate** [comment]
Indeed, GitHub's OAuth scopes are not fine-granular enough.

Apparently, it is possible to change the requested scope to other values by directly modifying the URL. I just set `scope=public_repo` in order to restrict the permissions granted to Anonymous GitHub. That worked well, your application got only those permissions (according to Settings -> Applications -> Authorized OAuth Apps).

However, I understand that anonymizing public repositories may not qualify for double-blind review processes. Do you have experience with that? AFAIS, reviewers are not supposed to actively reveal the authors' identities, and searching the internet/GitHub for repos with the same name or content would be just that. Another awkward work-around would be to anonymize a public repo and make it private afterwards.

Finally, another interesting observation is that I was still able to anonymize a private fork of a public repository (even after I removed the above-mentioned public_repo permission from Anonymous GitHub).

**Comment by tdurieux** [comment]
There are a lot of requests to anonymize private repositories. It is not a feature that I can remove. For the moment, the only solution that I see is that an organization that you trust host the service.

**Comment by henrikplate** [comment]
You got me wrong, there's no need to remove a feature! As mentioned, if users do not like to give you access to private repos, they can modify the redirect URL on the fly and specify whatever scope. As such, I was able to restrict access to `public_repo`.

Maybe my last question is whether you have some feedback whether computer science conferences raised some concerns or objections if a public repository was anonymized. As mentioned, AFAIK, conference reviewers are not meant to actively reveal author identities.

**Comment by tdurieux** [comment]
Sorry.
 
I never saw any rule related to public repositories, it will probably come in the future as the rules related to publishing pre-print.

On anonymous Github, "only" 22% of the anonymized repositories are private (this feature has been added one or two years ago which can also explain the difference).

**Comment by henrikplate** [comment]
Thank you so much, keep on the great work :)

**Comment by albertz** [comment]
I wonder that this is still not possible. I asked about it here: https://github.com/orgs/community/discussions/174347

Maybe we can make some feature request for GitHub on this somewhere? (Where?) I would think that this is a pretty common use case.

**Comment by tdurieux** [comment]
The alternative would be to move from AOuth to a GitHub App. But I do not have time to handle this change unfortunately.
