### ISSUE TITLE
Anonymous links redirection does not work properly

### ISSUE THREAD

**Issue by epicosy** [tdurieux/anonymous_github#57]
I have an anonymized repository with a README file that contains links to other anonymized repositories. When I click on the link it redirects but the session is the same as in the previous anonymized repository. You can check this issue by clicking on the link for SOSRepair in this [README file](https://anonymous.4open.science/r/SecureThemAll-0F57/README.md).

**Comment by tdurieux** [comment]
Indeed, I did not handle this case. It should not be too difficult to handle. I hope to find some time this week to fix it.

**Comment by tdurieux** [comment]
Thanks @epicosy, I fixed this bug!

ps: nice to see that you know RepairThemAll ;)

**Comment by epicosy** [comment]
Thanks, @tdurieux! RepairThemAll was quite helpful to adapt its concept to a different context. You are doing a great job!
