### ISSUE TITLE
Downloading the zip from the repository never finish 

### ISSUE THREAD

**Issue by SherylHYX** [tdurieux/anonymous_github#60]
Hi developers,

I have anonymized one repo with large files. I clicked on "force update" last week but it is still "downloading" till now. How could I ever fix the status to allow for updates?

Thanks in advance!

**Comment by tdurieux** [comment]
Could you send the id of your repository by email?

**Comment by SherylHYX** [comment]
> Could you send the id of your repository by email?

Email sent. Could you receive that?
