### ISSUE TITLE
Race condition when force update twice

### ISSUE THREAD

**Issue by deepeshhada** [tdurieux/anonymous_github#61]
Please look into this immediately. The README.md is very important for my work and for some reason it has disappeared!

**Comment by tdurieux** [comment]
Without more information I cannot do anything.

**Comment by deepeshhada** [comment]
It seems like there is some problem when you click on the "force refresh" button the second time before the first refresh hasn't completed. This made all the Github legacy files like README.md, License, etc., disappear. Issuing a fresh commit had solved this problem.

**Comment by tdurieux** [comment]
Ok thank you, I see the problem I will try to fix it in the future.
