### ISSUE TITLE
website 404

### ISSUE THREAD

**Issue by smallmax00** [tdurieux/anonymous_github#63]
It seems the website is 404 now?

**Comment by tdurieux** [comment]
Can you send me the link. It is working on my side.

**Comment by smallmax00** [comment]
> Can you send me the link. It is working on my side.

When I try to open http://anonymous.4open.science/ , I got the results of  'Virgin Media Child Safe settings have blocked this site', I am in UK, Don't know somewhat reason. However, I can open it with my mobile. While, my link still shows 404 when i try to open it, i think it's because of that issue.

**Comment by tdurieux** [comment]
I have no idea with Virgin blocks anonymous GitHub and I don't see any obvious way to contact them to understand what is happening. The only option that I see is that you disable this option in your Virgin account (it is enabled by default).

**Comment by smallmax00** [comment]
> I have no idea with Virgin blocks anonymous GitHub and I don't see any obvious way to contact them to understand what is happening. The only option that I see is that you disable this option in your Virgin account (it is enabled by default).

Thank you, I am worrying about my under reviewed paper, if the reviewer has the same issue as mine.

**Comment by tdurieux** [comment]
It is the first time that someone open an issue about this.

Can you access this IP: 51.15.227.110 (you should see "Welcome to nginx!")?

Also, when did you create your anonymization?

**Comment by smallmax00** [comment]
Yes, I can.

About 1 month ago

**Comment by tdurieux** [comment]
You can request whitelisting of the website at https://my.virginmedia.com/my-apps/websafe/feedback (I cannot do it, I don't have a virginmedia account)

**Comment by smallmax00** [comment]
Thank you.

**Comment by tdurieux** [comment]
I see that you own 2 repos and I can access both of them.

**Comment by smallmax00** [comment]
OK, Thank you. I think my case is very rare.
