### ISSUE TITLE
Inclusive language

### ISSUE THREAD

**Issue by EstherPlomp** [tdurieux/anonymous_github#64]
Hi there, love this initiative!

I noticed that on the main page the term 'double-blind' is used several times. This is ableist language and can easily be changed to 'double-anonymous' to be more inclusive. See here for some more information about ableist language: https://pwd.org.au/resources/disability-info/language-guide/ableist-language/

I hope this can be adjusted! 

Thanks for your time,
Esther

**Comment by tdurieux** [comment]
Thank you for pointing that to me. I will fix that!

**Comment by tdurieux** [comment]
Fixed!
