### ISSUE TITLE
can not render images

### ISSUE THREAD

**Issue by anonymityBoy** [tdurieux/anonymous_github#75]
I anonymized  a repo and image could show before.
However, the image has not rendered since 8:00 am Sep 7th 2021 (Beijing Time).
BTW,  I have refreshed the pages and updated figures many times.

In detail:
Before:
![image](https://user-images.githubusercontent.com/81273096/132317169-8ba49f71-ec10-4d9e-8128-82ae1cb0831f.png)

Now 
![image](https://user-images.githubusercontent.com/81273096/132317189-6a7ff8ba-6653-49f8-b423-4cf93832d55f.png)

**Comment by tdurieux** [comment]
Can you send me the link to your repository?

**Comment by anonymityBoy** [comment]
Sure. https://anonymous.4open.science/r/CodeSumToolbox

**Comment by kobiso** [comment]
I had the similar issue.
When I put `proxy mode: stream`, every image (png, gif) in README are not rendered.
- link: https://anonymous.4open.science/r/anonymous-mlsd-47D5/README.md

However, when I put `proxy mode: download`, there was no rendering issue.

**Comment by anonymityBoy** [comment]
I used `![fig](Fig/awesome.png)` .
BTW, the `awesome.png` was also not rendered

**Comment by tdurieux** [comment]
Thank you for the info, I found the bug. I deploy the fix shortly.

**Comment by anonymityBoy** [comment]
The figure Still can not rendered now in  https://anonymous.4open.science/r/CodeSumToolbox.
😆

**Comment by tdurieux** [comment]
It was cached by cloudflare.
It is correctly displayed now.

**Comment by anonymityBoy** [comment]
Still not correctly display in  https://anonymous.4open.science/r/CodeSumToolbox. (●ˇ∀ˇ●)

**Comment by tdurieux** [comment]
Remove your cache
![image](https://user-images.githubusercontent.com/5577568/132671189-10403cee-a34e-4ce4-b35c-642d54ee4f15.png)

**Comment by anonymityBoy** [comment]
Thanks
