### ISSUE TITLE
Force update the repo but miss out files

### ISSUE THREAD

**Issue by sigmod-sub-2022** [tdurieux/anonymous_github#76]
Even after forcing update the repo by putting down the commit number, the repo still shows the incorrect file status within the repo.

**Comment by sigmod-sub-2022** [comment]
![image](https://user-images.githubusercontent.com/86575246/132359778-d0fabe6d-09cf-4cfd-a972-74aa422b26a6.png)
I assume something is wrong with pulling updates from the Github repo?

**Comment by tdurieux** [comment]
No, everything should be ok. it is just bad UI. I am still working on it.
