### ISSUE TITLE
Force update not working again

### ISSUE THREAD

**Issue by Serendipity618** [tdurieux/anonymous_github#78]
I used "force update" and "edit" to update my repo, but both of them did not work. Could you please fix the problem?

**Comment by tdurieux** [comment]
What did not work exactly?

**Comment by up700** [comment]
> What did not work exactly?

I met the same problem. When I have updated the original repo, and then I used "force update", but the anonymous repo is not updated.

**Comment by tdurieux** [comment]
I only force the update when there is a more recent commit available.
Could you send me your repoId for me to double check?

**Comment by up700** [comment]
> I only force the update when there is a more recent commit available.
> Could you send me your repoId for me to double check?

I have sent an Email. Thank you a lot.

**Comment by tdurieux** [comment]
It seems to be up to date to me. You added "here" in your latest commit.
![image](https://user-images.githubusercontent.com/5577568/132686725-f9eb006f-a804-4210-b93b-3867116b685f.png)

**Comment by up700** [comment]
> It seems to be up to date to me. You added "here" in your latest commit.
> ![image](https://user-images.githubusercontent.com/5577568/132686725-f9eb006f-a804-4210-b93b-3867116b685f.png)
> 
> Maybe, you don't see the update due to some cache, please remove your browser cache and check again.

I get it. Thank you very much!

**Comment by Serendipity618** [comment]
My repo is updated this morning, though it takes a longer time than I expected. Thanks!

**Comment by flyboss** [comment]
I used "force update" to edit my readme.md, but I find it has not been updated for more than 48 hours and still used the content in the cache. I have to use “shift+F5” to force cache invalidation. So how can I set to make other people see the latest content without force cache invalidation?  Could you please help me?
