### ISSUE TITLE
ERRORS.repository_not_available

### ISSUE THREAD

**Issue by taidane** [tdurieux/anonymous_github#79]
Hello, 
today when I check my anonymous repo (I did nothing before), I accidentally find it stays `Error` state: 

```
ERRORS.repository_not_available
```
or
```
Anonymous Github is still processing the repository, it can take several minutes.
```

I tried to restore it using edit and update (stuck at the progress bar and still show `error`), remove and enable, but nothing worked.

How to fix this problem? **I still need to keep using my original repo ID.**

**Comment by tdurieux** [comment]
Can you send me the link to your repository?
Can you verify that you have access to the repository?

**Comment by taidane** [comment]
Yes, both I can. 
I have sent you an email with more information, hope to bring back my old link :)
