### ISSUE TITLE
Conference ID only accessible by the account that create the conference?

### ISSUE THREAD

**Issue by manathan1984** [tdurieux/anonymous_github#84]
One more potential bug!

I created the entry of the conference (in the free tier for now) and the ID is “SIGMOD22”
When I am trying to anonymize a repo, when I put the ID in the appropriate textbox I see the info of the conference. 

However, when someone else uses the ID, the conference info does not pop up. Can you double-check this?
If you need more details about the problem I can share screenshots.

**Comment by tdurieux** [comment]
Fixed with 07750f7a646a965f60e21e7a9e523096ef0f0a50
