### ISSUE TITLE
[Urgent] After changing the github repo's name, the anonymous repo is not updating anymore

### ISSUE THREAD

**Issue by tempdemoxyz** [tdurieux/anonymous_github#85]
Could you please help to let me know the solution? I have used force push, and it doesn't work. Thanks!

**Comment by jundev1l2l** [comment]
Same here. I have not changed the repo's name, and even checked that the commit number in anonymous_github is the same as the latest commit in github. However, the anonymous repo is not updated.

**Comment by tdurieux** [comment]
did you remove your browser cache?
Can you send me your repo id?

**Comment by anonymous-ac** [comment]
I also have the same problem. I updated the pdf document in my repo but the anonymous repo was not updating anymore.

**Comment by tdurieux** [comment]
You should remove your browse cache.
