### ISSUE TITLE
Force cache invalidation

### ISSUE THREAD

**Issue by flyboss** [tdurieux/anonymous_github#86]
I used "force update" to edit my readme.md, but I find it has not been updated for more than 48 hours and still used the content in the cache. I have to use “shift+F5” to force cache invalidation with the help of #78 .
So how can I set to make other people see the latest content without force cache invalidation? Could you please help me?

**Comment by flyboss** [comment]
I find the request header of "readme.md" has an attribute "cache-control: max-age=21600000". Maybe this value is too big?

**Comment by tdurieux** [comment]
It should be 300: https://github.com/tdurieux/anonymous_github/blob/main/src/routes/file.ts#L37

**Comment by flyboss** [comment]
Thank you！
