### ISSUE TITLE
Cache problem

### ISSUE THREAD

**Issue by flyboss** [tdurieux/anonymous_github#87]
hello, I notice the [commit](https://github.com/tdurieux/anonymous_github/commit/89e9c60942f30a09fb72c5f43335895427900fe9) updated cache duration. But before this commit, I have published my link to others and the files still have long cache duration. How can I fix this problem. Could you help me? Thank you very much.

**Comment by tdurieux** [comment]
It is most likely will only happen to you, because you visited your repo, it will not happen if you never visited it. 
Unfortunately, I am not able to invalidate the browser cache remotely.

**Comment by flyboss** [comment]
I get it. Thank you very much.
