### ISSUE TITLE
broken repo

### ISSUE THREAD

**Issue by georgestod** [tdurieux/anonymous_github#88]
Hi,
First of all, thanks a lot for your amazing work!
I have a broken repo: after adding some extra keywords, the repo does not move from the 'preparing' state. I have waited around 12 hours. For the moment I created a new repo, which works great but would like to delete the broken one. How can I do that?

Thanks!

**Comment by tdurieux** [comment]
I am working on it,  I will try to find the reason that blocks you in the preparing state.
