### ISSUE TITLE
"The repository is not found." bug when claiming repo

### ISSUE THREAD

**Issue by qqliu** [tdurieux/anonymous_github#91]
First, thanks for the great work on this project! It's been tremendously helpful in my paper submissions.

I was trying to claim an already anonymized repo in my profile but the claim page kept giving the above error: "The repository is not found." even when I provide it with the correct Github URL link (for a public repo). Help greatly appreciated here, thanks!

**Comment by tdurieux** [comment]
I fixed the problem, you should be able to claim your repository.
