### ISSUE TITLE
Can not activate "Github page" button

### ISSUE THREAD

**Issue by james-sungjae-lee** [tdurieux/anonymous_github#92]
Hi, I'm working on anonymous github for my research project,

and I want to publish my github page, but I can not activate "Github page" button.

![image](https://user-images.githubusercontent.com/20024627/135577046-f07f1af6-dfde-4920-9d1e-7fd6cd680424.png)

Is there any condition to activate button?

Without activate button, when I access to anonymous github page address, I received the massage

{"error": "page_not_activated"}

So, anyone can explain how to setting github page with anonymous github?

**Comment by Lifedecoder** [comment]
Hi james, have you figure out the solutions about how to activate page on anonymous site?

**Comment by PussyCat0700** [comment]
I encountered the same thing and this is what I did to solve it:

1. Ensure GH pages deployment is on the same branch, and in my case GH pages deployment Source is `Deploy from a branch`.
2. Ensure the repo has a running GH pages deployment. (Note that if you are not on an enterprise Github account, you will not be able to publish a website from a private repo so you have to fall back to a public one)
3. If you have modified your GH pages recently, go to anonymous github page and select `force update` to refresh repo status of your anonymous repo

In my case the last option solved the problem, as addressed by PR proposed by CLAUDE here https://github.com/tdurieux/anonymous_github/pull/612.
