### ISSUE TITLE
Claiming someone else's repository possible?

### ISSUE THREAD

**Issue by HTenkanen** [tdurieux/anonymous_github#93]
Hi! First of all, thanks for a great project!

I just chatted about this with a colleague and we think this is an awesome tool, but came thinking about the security. It seems that it is possible to anonymize someone else's repository..? I tested to anonymize my colleagues repo and it worked. Hence, wouldn't there be a risk of someone claiming a public repository that is not theirs? I wonder if you have considered this aspect?

Best,
Henrikki

**Comment by server-python** [comment]
https://github.com/tdurieux/anonymous_github/issues/24:)

**Comment by tdurieux** [comment]
I dont really see the problem because you can put the repo of anybody in your paper and therefore claim the ownership (or create a zip file with the code of someone else).
I dont think there will ever be a tool that will project against plagiarism.

(maybe I miss understood your question)

**Comment by server-python** [comment]
:(

**Comment by server-python** [comment]
:)

‫‪Thomas Durieux‬‏ ***@***.***‬‏> در تاریخ چهارشنبه ۱۰ اوت
۲۰۲۲ ساعت ۱۱:۱۴ نوشت:‬

**Comment by server-python** [comment]
خب داداش اینو با مترجم گوگل ترجمه کن:)
اشتراک رو لغو کن:)

‫‪Server Code‬‏ ***@***.***‬‏> در تاریخ پنجشنبه ۱۱ اوت ۲۰۲۲
ساعت ۹:۵۱ نوشت:‬
