### ISSUE TITLE
Large repositories generate an error

### ISSUE THREAD

**Issue by alessandropellegrini** [tdurieux/anonymous_github#94]
Hi, thanks for this great tool!

I have noticed that if the git repository is very large (a huge number of branches, and a huge commit history), the service fails when loading the repository with:

```
ERRORS.AnonymizedRepository validation failed: size.storage: Cast to Number failed for value "86229300417237122403232[object Object]208355639111242222659529376849524236590656477" (type string) at path "size.storage"
```

An example is the linux kernel tree: https://anonymous.4open.science/r/linux54x/

**Comment by romits800** [comment]
Same issue here. Any chance on fixing this?

**Comment by server-python** [comment]
https://github.com/tdurieux/anonymous_github/issues/24:)
