### ISSUE TITLE
Demo repo not fully anonymized

### ISSUE THREAD

**Issue by andreas-zeller** [tdurieux/anonymous_github#96]
Hi folks – great stuff! But the demo repo lists "tdurieux" as a Docker owner, which I assume reveals the author.

**Comment by tdurieux** [comment]
Hi,

I suppose you meant this repo: https://anonymous.4open.science/r/840c8c57-3c32-451e-bf12-0e20be300389/docker-compose.yml
tdurieux was not in the list of terms to anonymize, I fixed it :)
