### ISSUE TITLE
Time stamp feature 

### ISSUE THREAD

**Issue by bertjiazheng** [tdurieux/anonymous_github#97]
Hi, 

Thanks for creating such a nice project. This is very useful for a double-blind paper reviewing. However, some conferences require the repo should not be modified after the submission due date. I wonder it is possible to add this new feature.

Best,
Jia

**Comment by tdurieux** [comment]
Thank you @bertjiazheng 
Do you mean to display the date of the commit or when the repository has been anonymized?

**Comment by bertjiazheng** [comment]
Yes, I think either one is ok.

**Comment by bertjiazheng** [comment]
Any plan for this feature?

**Comment by tdurieux** [comment]
Yes, but only when I have some time to handle it or when someone open a PR ;)

**Comment by tdurieux** [comment]
I added the last time the repository was updated. It is not when the commit has been pushed but when anonymous GitHub downloaded the latest change.
