### ISSUE TITLE
Errors loading anonymized repositories

### ISSUE THREAD

**Issue by sbnietert** [tdurieux/anonymous_github#98]
Currently, if I view the example anonymized repo (https://anonymous.4open.science/r/840c8c57-3c32-451e-bf12-0e20be300389/), or one of my own, I simply see the message "ERRORS! Empty file!". Login via GitHub also seems to be down, with "Internal Server Error" appearing when I attempt to load the login page.

**Comment by yoonseok312** [comment]
Same issue here. As I posted my anonymized repo as the source code of a paper under review, can I know when this issue will be resolved?

**Comment by SwapCT** [comment]
It looks like an intermittent failure or overload as it works sometimes.

**Comment by felix-engelmann** [comment]
It looks like an intermittent failure or overload as it works sometimes.

**Comment by tdurieux** [comment]
Hi all,

The disk of the server was full. I resolve the problem and it is now working again!
