### ISSUE TITLE
New commits not showing up in README

### ISSUE THREAD

**Issue by flpgrz** [tdurieux/anonymous_github#99]
Hello, I had (1) initialized a repo with a README, then (2) created an anonymous repo, then (3) commited some changes.

At step (3) I added some extra files, which show up correctly in the anonymous repo.
However, at step (3) I also edited the README. The README however is updating in the anonymous repo, and still seems to be at the initial commit stage.

**Comment by cmougan** [comment]
@flpgrz , Did. you manage? I have the same issue. Is just a matter of time?

**Comment by flpgrz** [comment]
@cmougan, I pushed the refresh button, then it took some minutes, but it eventually refreshed. I suggest to wait a bit
